[package]
name = "axtask"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS task management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axtask"
documentation = "https://arceos-org.github.io/arceos/axtask/index.html"

[features]
default = ["irq"]

multitask = []
irq = []
tls = []
preempt = []
smp = []

sched-fifo = []
sched-rr = []
sched-cfs = []

test = []

[dependencies]
#cfg-if = "1.0"
log = "=0.4.21"
axhal = { workspace = true }
linux_adaptor = { workspace = true }
linux_config = { workspace = true }
axconfig = { workspace = true }
percpu = { workspace = true, optional = true }
#kspin = { version = "0.1", optional = true }
#lazyinit = { version = "0.2" }
#memory_addr = { version = "0.4", optional = true }
#timer_list = { version = "0.1", optional = true }
#kernel_guard = { version = "0.1", optional = true }
#crate_interface = { version = "0.1", optional = true }
cpumask = { version = "0.1" }
#axsched = { version = "0.3", optional = true }
axstage = { workspace = true }
inventory = { workspace = true }

[dev-dependencies]
#rand = "0.9"
#axhal = { workspace = true, features = ["fp-simd"] }
#axtask = { workspace = true, features = ["test", "multitask"] }
