# Makefile for `kernel`

obj-y += resource.o workqueue.o kthread.o
obj-y += nsproxy.o cpu.o user_namespace.o
obj-y += panic.o exit.o cred.o softirq.o
obj-y += extable.o tracepoint.o jump_label.o
obj-y += irq_work.o params.o reboot.o
obj-y += notifier.o smp.o async.o
