# Makefile for `block`

obj-y += blk-core.o
obj-y += genhd.o
obj-y += blk-mq.o
obj-y += blk-mq-tag.o
obj-y += bdev.o
obj-y += bio.o
obj-y += blk-stat.o
obj-y += blk-settings.o
obj-y += blk-flush.o
obj-y += blk-mq-sched.o
obj-y += blk-mq-virtio.o
obj-y += blk-mq-cpumap.o
obj-y += blk-mq-sysfs.o
obj-y += blk-merge.o
obj-y += blk-timeout.o
obj-y += blk-map.o
obj-y += blk-rq-qos.o
obj-y += elevator.o
obj-y += mq-deadline.o
obj-y += fops.o

#obj-y += early-lookup.o

obj-y += partitions/
