# Makefile for `arch/riscv/kernel`

obj-y += sbi.o
obj-y += sbi-ipi.o
obj-y += sbi_ecall.o
obj-y += setup.o
obj-y += smpboot.o
obj-y += smp.o
obj-y += traps.o
obj-y += irq.o
obj-y += stacktrace.o
obj-y += cpu.o
obj-y += cpufeature.o
obj-y += jump_label.o
obj-y += process.o
obj-y += vector.o
obj-y += time.o
obj-y += vendor_extensions.o
obj-y += patch.o
obj-y += cpu_ops.o
obj-y += cpu_ops_sbi.o
obj-y += cacheinfo.o
obj-y += signal.o
obj-y += syscall_table.o
obj-y += compat_syscall_table.o
obj-y += sys_riscv.o
obj-y += alternative.o
obj-y += fpu.o
obj-y += traps_misaligned.o
obj-y += sys_hwprobe.o
obj-y += unaligned_access_speed.o
obj-y += copy-unaligned.o
obj-y += reset.o

#obj-y += acpi.o

obj-y += vdso.o

obj-y += vdso/
obj-y += compat_vdso/
obj-y += vendor_extensions/
