# Makefile for `arch/riscv/kernel`

#obj-y += sbi.o sbi-ipi.o
obj-y += sbi_ecall.o
obj-y += setup.o

#obj-y += stacktrace.o

#obj-y += jump_label.o
#obj-y += patch.o
#obj-y += reset.o
#obj-y += smpboot.o
#obj-y += smp.o
#obj-y += cpu.o
#obj-y += cpu_ops.o
#obj-y += cpu_ops_sbi.o
#obj-y += cpufeature.o
#obj-y += irq.o
#obj-y += acpi.o
