[workspace]
resolver = "2"

members = [
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdriver",
    "modules/axfs",
    "modules/axhal",
    "modules/axlog",
    "modules/axdma",
    "modules/axnet",
    "modules/axns",
    "modules/axsync",
    "modules/axipi",

    "api/axfeat",
    "api/arceos_api",
    "api/arceos_posix_api",

    "ulib/axstd",
    "ulib/axlibc",

    "examples/helloworld",
    "examples/helloworld-myplat",
    "examples/httpclient",
    "examples/httpserver",
    "examples/shell",

    "examples/memtest",
    "examples/exception",
    "examples/task/sleep",
    "examples/task/yield",

    "platforms/axplat-riscv64-dp1000",

    "crates/axlds",
    "crates/axtask_lx",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Yuekai Jia <equation618@gmail.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
documentation = "https://arceos-org.github.io/arceos"
repository = "https://github.com/arceos-org/arceos"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]

[workspace.dependencies]
axstd = { path = "ulib/axstd" }
axlibc = { path = "ulib/axlibc" }

arceos_api = { path = "api/arceos_api" }
arceos_posix_api = { path = "api/arceos_posix_api" }
axfeat = { path = "api/axfeat" }

axconfig = { path = "modules/axconfig" }
axdisplay = { path = "modules/axdisplay" }
axdriver = { path = "modules/axdriver" }
axfs = { path = "modules/axfs" }
axhal = { path = "modules/axhal" }
axlog = { path = "modules/axlog" }
axnet = { path = "modules/axnet" }
axns = { path = "modules/axns" }
axsync = { path = "modules/axsync" }
axdma = { path = "modules/axdma" }
axipi = { path = "modules/axipi" }

axruntime = { path = "crates/axruntime_lx" }
axlds = { path = "crates/axlds" }
axtask = { path = "crates/axtask_lx" }
axcpu = { path = "crates/axcpu_lx" }
axalloc = { path = "crates/axalloc_lx" }
axmm = { path = "crates/axmm_lx" }
linux_adaptor = { path = "crates/linux_adaptor" }

[profile.release]
lto = true
