[workspace]
resolver = "2"

members = [
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdma",
    "modules/axnet",
    "modules/axns",
    "modules/axsync",
    "modules/axipi",

    "api/arceos_api",
    "api/arceos_posix_api",

    "ulib/axstd",
    "ulib/axlibc",

    "examples/helloworld",
    "examples/helloworld-myplat",
    "examples/httpclient",
    "examples/httpserver",
    "examples/shell",

    "examples/memtest",
    "examples/exception",
    "examples/task/sleep",
    "examples/task/yield",
    "examples/task/priority",
    "examples/task/parallel",
    "examples/task/irq",
    "examples/task/wait_queue",
    "examples/task/affinity",

    "examples/driver/block",

    "platforms/axplat-riscv64-dp1000",

    "crates/axlds",
    "crates/axtask_lx",
    "crates/axstage",
    "crates/axlog_ex",
    "crates/axmem_lx",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Yuekai Jia <equation618@gmail.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
documentation = "https://arceos-org.github.io/arceos"
repository = "https://github.com/arceos-org/arceos"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]

[workspace.dependencies]
axstd = { path = "ulib/axstd" }
axlibc = { path = "ulib/axlibc" }

arceos_api = { path = "api/arceos_api" }
arceos_posix_api = { path = "api/arceos_posix_api" }
axfeat = { path = "crates/axfeat_lx", package = "axfeat_lx" }

axconfig = { path = "modules/axconfig" }
axdisplay = { path = "modules/axdisplay" }
axlog = { path = "crates/axlog_ex", package = "axlog_ex" }
axnet = { path = "modules/axnet" }
axns = { path = "modules/axns" }
axsync = { path = "modules/axsync" }
axdma = { path = "modules/axdma" }
axipi = { path = "modules/axipi" }

axstage = { path = "crates/axstage" }
axhal = { path = "crates/axhal_lx", package = "axhal_lx" }
axruntime = { path = "crates/axruntime_lx", package = "axruntime_lx" }
axlds = { path = "crates/axlds" }
axtask = { path = "crates/axtask_lx" }
axcpu = { path = "crates/axcpu_lx" }
axalloc = { path = "crates/axalloc_lx" }
axmm = { path = "crates/axmm_lx" }
axmem = { path = "crates/axmem_lx", package = "axmem_lx" }
axdriver = { path = "crates/axdriver_lx", package = "axdriver_lx" }
axfs = { path = "crates/axfs_lx", package = "axfs_lx" }
axfs_devfs = { path = "crates/axfs_devfs_lx", package = "axfs_devfs_lx" }
linux_adaptor = { path = "crates/linux_adaptor" }
linux_config = { path = "crates/linux_config" }
percpu = { path = "crates/percpu_lx" }
percpu_macros = { path = "crates/percpu_macros_lx" }
inventory = "0.3"
log = "=0.4.21"
axplat = "0.3"

[profile.release]
lto = true
