# Makefile for `arch/riscv/kernel`

obj-y += stacktrace.o
obj-y += jump_label.o
obj-y += patch.o
obj-y += reset.o
obj-y += smp.o
obj-y += setup.o
obj-y += irq.o
obj-y += acpi.o
obj-y += sbi.o sbi_ecall.o sbi-ipi.o
