# Makefile for `arch/riscv/mm`

CFLAGS_init.o := -mcmodel=medany

obj-y += init.o
obj-y += dma-noncoherent.o
obj-y += cacheflush.o
obj-y += pgtable.o
obj-y += tlbflush.o
obj-y += context.o
obj-y += fault.o
