# Makefile for `drivers`

obj-y += of/
obj-y += base/
obj-y += irqchip/
obj-y += clocksource/
obj-y += clk/
obj-y += char/
obj-y += cpuidle/
#obj-y += gpio/
#obj-y += pci/
#obj-y += virtio/
#obj-y += block/
#obj-y += nvme/
#obj-y += mtd/
#obj-y += spi/
#obj-y += power/
#obj-y += firmware/
#obj-y += nvmem/
