# Makefile for `drivers`

obj-y += irqchip/
obj-y += gpio/
obj-y += pci/
obj-y += clk/
obj-y += virtio/
obj-y += char/
obj-y += base/
obj-y += block/
obj-y += nvme/
obj-y += mtd/
obj-y += spi/
obj-y += power/
obj-y += firmware/
obj-y += of/
obj-y += nvmem/
