# Makefile for `kernel`

obj-y += core.o
obj-y += memalloc.o
obj-y += helpers.o
obj-y += bpf_iter.o
obj-y += map_iter.o
obj-y += btf.o
obj-y += verifier.o
obj-y += tnum.o
obj-y += syscall.o
obj-y += offload.o
obj-y += disasm.o
obj-y += arraymap.o
obj-y += hashtab.o
obj-y += stackmap.o
obj-y += lpm_trie.o
obj-y += devmap.o
obj-y += cpumap.o
obj-y += reuseport_array.o
obj-y += queue_stack_maps.o
obj-y += ringbuf.o
obj-y += bloom_filter.o
obj-y += bpf_task_storage.o
obj-y += task_iter.o
obj-y += net_namespace.o
obj-y += tcx.o
