# Makefile for `drivers/pci`

obj-y += ecam.o access.o probe.o pci.o search.o
obj-y += pci-driver.o of.o bus.o devres.o setup-bus.o
obj-y += slot.o quirks.o host-bridge.o vc.o vpd.o
obj-y += setup-res.o irq.o

obj-y += msi/
obj-y += pcie/
obj-y += controller/
