# Makefile for `mm`

obj-y += debug.o
obj-y += memblock.o
obj-y += memory.o

#obj-y += mm_init.o page_alloc.o filemap.o page-writeback.o
#obj-y += slub.o percpu.o slab_common.o util.o swap.o
#obj-y += debug_page_alloc.o ioremap.o mempool.o
#obj-y += backing-dev.o list_lru.o shrinker.o
#obj-y += truncate.o workingset.o readahead.o
#obj-y += rmap.o vmstat.o maccess.o vmalloc.o dmapool.o
#obj-y += page_reporting.o
#obj-y += mmzone.o
#obj-y += interval_tree.o
