# Makefile for `mm`

obj-y += debug.o
obj-y += memblock.o
obj-y += memory.o
obj-y += memtest.o
obj-y += mm_init.o
obj-y += mmzone.o
obj-y += vmstat.o
obj-y += page_alloc.o
obj-y += page_reporting.o
obj-y += slub.o
obj-y += slab_common.o
obj-y += debug_page_alloc.o
obj-y += percpu.o
obj-y += vmalloc.o
obj-y += util.o
obj-y += shrinker.o
obj-y += init-mm.o
obj-y += swap.o
obj-y += maccess.o
obj-y += mmap.o
obj-y += oom_kill.o

#obj-y += filemap.o page-writeback.o
#obj-y += ioremap.o mempool.o
#obj-y += backing-dev.o list_lru.o
#obj-y += truncate.o workingset.o readahead.o
#obj-y += rmap.o dmapool.o
#obj-y += interval_tree.o
