# Makefile for `net/core`

obj-y += dev.o
obj-y += dev_addr_lists.o
obj-y += neighbour.o
obj-y += sock.o
obj-y += skbuff.o
obj-y += net_namespace.o
obj-y += net-traces.o
obj-y += rtnetlink.o
obj-y += link_watch.o
obj-y += page_pool.o
obj-y += page_pool_user.o
obj-y += netdev-genl-gen.o
obj-y += xdp.o
obj-y += gro.o
obj-y += gen_stats.o
