# Makefile for buildging subdirs

subdir := $(dir $(obj))
$(info --- $(obj) ---)

obj-y :=

include $(CURDIR)/scripts/Makefile.include
include $(subdir)Makefile

obj-y := $(addprefix $(subdir), $(obj-y))

_build: $(obj)

$(obj): $(obj-y) FORCE
	$(Q)rm -f $@
	$(Q)echo $(obj-y) > $@

$(subdir)%.o: $(subdir)%.c
	$(Q)$(CC) $(CFLAGS) -DKBUILD_MODFILE='"$@"' -DKBUILD_BASENAME='"$@"' -DKBUILD_MODNAME='"$@"' -c -o $@ $<

FORCE:

.PHONY: _build FORCE
