# Makefile for `drivers/base`

CFLAGS_trace.o := -I$(curdir)

obj-y += core.o
obj-y += property.o
obj-y += swnode.o
obj-y += cpu.o
obj-y += arch_topology.o
obj-y += cacheinfo.o
obj-y += platform.o
obj-y += class.o
obj-y += bus.o
obj-y += dd.o
obj-y += driver.o

#obj-y += property.o syscore.o
#obj-y += devres.o trace.o
#obj-y += map.o firmware.o

obj-y += power/
#obj-y += regmap/
