# Makefile for `kernel/trace`

CFLAGS_bpf_trace.o := -I$(curdir)

obj-y += trace_syscalls.o
obj-y += power-traces.o
obj-y += rpm-traces.o
obj-y += bpf_trace.o

#obj-y += trace.o

#obj-y += trace_events.o
#obj-y += trace_output.o pid_list.o trace_events_filter.o
#obj-y += ring_buffer.o ftrace.o trace_seq.o
#obj-y += trace_functions.o trace_nop.o
