# Makefile for `kernel/trace`

obj-y += trace_syscalls.o
obj-y += power-traces.o

#obj-y += trace.o

#obj-y += trace_events.o
#obj-y += trace_output.o pid_list.o trace_events_filter.o
#obj-y += ring_buffer.o ftrace.o trace_seq.o
#obj-y += trace_functions.o trace_nop.o
