# Makefile for `kernel/sched`

obj-y += core.o
obj-y += wait.o
obj-y += wait_bit.o
obj-y += swait.o
obj-y += completion.o
obj-y += topology.o
obj-y += debug.o
obj-y += syscalls.o

obj-y += stop_task.o
obj-y += fair.o
obj-y += idle.o
obj-y += rt.o
obj-y += deadline.o

obj-y += cpudeadline.o
obj-y += cpupri.o
obj-y += loadavg.o
