# Makefile for `fs/ext4`

obj-y += super.o balloc.o bitmap.o block_validity.o
obj-y += ext4_jbd2.o extents.o extents_status.o file.o dir.o
obj-y += fsmap.o fsync.o hash.o ialloc.o indirect.o
obj-y += inline.o inode.o inode-test.o ioctl.o mballoc.o
obj-y += migrate.o mmp.o move_extent.o namei.o page-io.o
obj-y += readpage.o resize.o symlink.o sysfs.o
obj-y += verity.o xattr.o xattr_hurd.o orphan.o acl.o
obj-y += xattr_trusted.o xattr_user.o fast_commit.o
obj-y += xattr_security.o
