# Makefile for 'driver/base/regmap'

CFLAGS_regmap.o := -I$(curdir)

obj-y += regmap-mmio.o
obj-y += regmap.o
obj-y += regcache.o
obj-y += regcache-rbtree.o
obj-y += regcache-maple.o
obj-y += regcache-flat.o
