# Makefile for `drivers/of`

obj-y += base.o
obj-y += property.o
obj-y += fdt.o
obj-y += kobj.o
obj-y += irq.o
obj-y += early_fdt.o
obj-y += of_reserved_mem.o
obj-y += empty_root.dtb.o
obj-y += cpu.o

#obj-y += address.o
#obj-y += platform.o device.o
