#include <linux/printk.h>
#include "adaptor.h"

CL_MINE(sprint_symbol_build_id)
CL_MINE(sprint_backtrace)
CL_MINE(sprint_symbol_no_offset)
CL_MINE(sprint_backtrace_build_id)
CL_MINE(__brelse)

CL_MINE(__clk_get_name)
CL_MINE(time64_to_tm)
CL_MINE(siphash_1u64)
CL_MINE(has_capability_noaudit)
CL_MINE(errname)

CL_MINE(trace_event_buffer_reserve)
CL_MINE(trace_event_buffer_commit)
CL_MINE(trace_raw_output_prep)
CL_MINE(trace_event_printf)
CL_MINE(trace_handle_return)

CL_MINE(__trace_trigger_soft_disabled)
CL_MINE(perf_trace_buf_alloc)
CL_MINE(perf_trace_run_bpf_submit)

CL_MINE(memblock_mark_hotplug)

CL_MINE(_copy_from_user)

CL_MINE(print_worker_info)

CL_MINE(bpf_trace_run1)
CL_MINE(bpf_trace_run2)
CL_MINE(bpf_trace_run3)
CL_MINE(bpf_trace_run4)
CL_MINE(bpf_trace_run5)
CL_MINE(bpf_trace_run6)
CL_MINE(bpf_trace_run7)
CL_MINE(bpf_trace_run9)
CL_MINE(bpf_trace_run10)
CL_MINE(bpf_trace_run12)
CL_MINE(trace_print_bitmask_seq)
CL_MINE(trace_print_flags_seq)
CL_MINE(trace_print_symbols_seq)
CL_MINE(add_taint)

CL_MINE(__kernel_map_pages)

CL_MINE(node_dirty_ok)
CL_MINE(wakeup_kswapd)

CL_MINE(decay_pcp_high)
CL_MINE(__seq_puts)
CL_MINE(seq_put_decimal_ull)
CL_MINE(seq_putc)
CL_MINE(seq_write)
CL_MINE(round_jiffies_relative)
CL_MINE(seq_open)
CL_MINE(seq_printf)
CL_MINE(schedule_on_each_cpu)
CL_MINE(delayed_work_timer_fn)
CL_MINE(seq_lseek)
CL_MINE(seq_read)
CL_MINE(seq_release)

CL_MINE(trace_event_reg)
CL_MINE(trace_event_raw_init)

CL_MINE(osq_lock)
CL_MINE(osq_unlock)
CL_MINE(io_schedule_prepare)
CL_MINE(io_schedule_finish)

CL_MINE(pcpu_get_vm_areas)

CL_MINE(flush_tlb_kernel_range)
CL_MINE(print_tracking)
CL_MINE(sysfs_slab_add)
CL_MINE(debugfs_slab_add)

CL_MINE(stack_trace_save)
CL_MINE(stack_depot_save)
CL_MINE(kmalloc_fix_flags)
CL_MINE(gfp_pfmemalloc_allowed)

CL_MINE(sysfs_emit)
CL_MINE(sysfs_emit_at)
CL_MINE(kmem_cache_shrink)
CL_MINE(slab_kmem_cache_release)
CL_MINE(kobject_del)
CL_MINE(flush_work)
CL_MINE(validate_slab_cache)
CL_MINE(warn_alloc)
CL_MINE(stack_depot_init)

CL_MINE(purge_fragmented_blocks_allcpus)

CL_MINE(flush_tlb_page)

CL_MINE(do_trap_insn_misaligned)
CL_MINE(do_trap_insn_fault)
CL_MINE(do_trap_insn_illegal)
CL_MINE(do_trap_load_misaligned)
CL_MINE(do_trap_load_fault)
CL_MINE(do_trap_store_misaligned)
CL_MINE(do_trap_ecall_u)
CL_MINE(do_trap_unknown)

CL_MINE(show_ipi_stats)
CL_MINE(free_huge_folio)

CL_MINE(irq_free_descs)

CL_MINE(io_schedule_timeout)
CL_MINE(task_curr)
CL_MINE(kstat)
CL_MINE(kernel_cpustat)
CL_MINE(nr_context_switches_cpu)

CL_MINE(mod_delayed_work_on)
CL_MINE(rcu_segcblist_entrain)
CL_MINE(schedule_timeout_idle)
CL_MINE(tracing_off)
CL_MINE(ftrace_dump)
CL_MINE(resched_cpu)
CL_MINE(kthread_queue_work)
CL_MINE(kthread_flush_work)

CL_MINE(irq_work_queue_on)
CL_MINE(rcu_segcblist_first_pend_cb)
CL_MINE(nbcon_cpu_emergency_enter)
CL_MINE(nbcon_cpu_emergency_exit)
CL_MINE(sched_show_task)
CL_MINE(dump_cpu_task)
CL_MINE(init_wait_entry)
CL_MINE(prepare_to_wait_event)

CL_MINE(finish_wait)
CL_MINE(kmem_cache_free_bulk)
CL_MINE(queue_rcu_work)
CL_MINE(flush_rcu_work)
CL_MINE(rcu_segcblist_merge)
CL_MINE(rcu_segcblist_disable)
CL_MINE(rcu_segcblist_first_cb)
CL_MINE(nr_context_switches)

CL_MINE(kmem_dump_obj)
CL_MINE(task_call_func)
CL_MINE(__put_task_struct)
CL_MINE(bitmap_parselist)
CL_MINE(cancel_work_sync)
CL_MINE(irq_domain_deactivate_irq)
CL_MINE(kthread_stop_put)
CL_MINE(proc_mkdir)

CL_MINE(wait_for_completion_state)
CL_MINE(irq_work_queue)
CL_MINE(housekeeping_affine)
CL_MINE(idle_task)
CL_MINE(add_timer)
CL_MINE(cpu_curr_snapshot)

CL_MINE(irqentry_exit_to_user_mode)

CL_MINE(riscv_get_mvendorid)
CL_MINE(riscv_get_marchid)
CL_MINE(patch_text_nosync)
CL_MINE(riscv_alternative_fix_offsets)
CL_MINE(irq_disable)
CL_MINE(proc_dointvec_minmax)
CL_MINE(sysctl_vals)
CL_MINE(proc_douintvec)

CL_MINE(uprobe_single_step_handler)
CL_MINE(uprobe_breakpoint_handler)
CL_MINE(do_trap)
CL_MINE(force_sig_fault)
CL_MINE(fixup_exception)
CL_MINE(__asm_copy_to_user)
CL_MINE(__asm_copy_from_user)
CL_MINE(strncpy_from_user)
CL_MINE(strnlen_user)

CL_MINE(cpudl_cleanup)
CL_MINE(housekeeping_any_cpu)

CL_MINE(call_trace_sched_update_nr_running)
CL_MINE(cpuidle_find_deepest_state)
CL_MINE(cpuidle_enter)
CL_MINE(cpuhp_report_idle_dead)
CL_MINE(cpuidle_select)
CL_MINE(tick_nohz_tick_stopped)
CL_MINE(cpuidle_reflect)
CL_MINE(cpuidle_enter_s2idle)
CL_MINE(tick_nohz_idle_retain_tick)

CL_MINE(cpuidle_use_deepest_state)
CL_MINE(proc_dointvec)
CL_MINE(cpupri_find)

CL_MINE(cpupri_find_fitness)
CL_MINE(double_rq_lock)
CL_MINE(plist_del)
CL_MINE(plist_add)
CL_MINE(sched_get_rd)
CL_MINE(cpufreq_update_util_data)
CL_MINE(sched_put_rd)

CL_MINE(group_balance_cpu)
CL_MINE(switch_mm)
CL_MINE(partition_sched_domains)
CL_MINE(smp_call_function_single_async)
CL_MINE(init_wait_var_entry)

CL_MINE(sched_init_domains)
CL_MINE(trace_output_call)
CL_MINE(print_cfs_rq)
CL_MINE(print_rt_rq)

CL_MINE(cpudl_find)
CL_MINE(cpudl_clear)
CL_MINE(cpudl_set)
CL_MINE(cpudl_clear_freecpu)
CL_MINE(hrtimer_forward)
CL_MINE(print_dl_rq)
CL_MINE(proc_douintvec_minmax)
CL_MINE(cpupri_cleanup)
CL_MINE(profile_hits)

CL_MINE(freezing_slow_path)
CL_MINE(force_sig)
CL_MINE(proc_dobool)

CL_MINE(fasync_helper)
CL_MINE(proc_dostring)
CL_MINE(_copy_to_iter)
CL_MINE(ktime_get_seconds)
CL_MINE(_copy_from_iter)
CL_MINE(schedule_timeout_interruptible)
CL_MINE(capable)
CL_MINE(__might_fault)
CL_MINE(import_ubuf)

CL_MINE(try_to_del_timer_sync)
CL_MINE(atomic_notifier_call_chain)
CL_MINE(kill_fasync)
CL_MINE(noop_llseek)
CL_MINE(compat_ptr_ioctl)
CL_MINE(iter_file_splice_write)
CL_MINE(copy_splice_read)
CL_MINE(trace_define_field)
CL_MINE(syscall_exit_register)
CL_MINE(syscall_enter_register)

CL_MINE(free_task)
CL_MINE(abort_creds)
CL_MINE(put_ucounts)
CL_MINE(create_user_ns)
CL_MINE(set_cred_ucounts)
CL_MINE(__put_cred)
CL_MINE(install_thread_keyring_to_cred)
CL_MINE(dec_rlimit_ucounts)
CL_MINE(exit_creds)
CL_MINE(sched_cancel_fork)
CL_MINE(perf_event_free_task)
CL_MINE(__audit_free)
CL_MINE(security_task_free)
CL_MINE(flush_signal_handlers)

CL_MINE(set_memory_ro)
CL_MINE(apply_early_boot_alternatives)
CL_MINE(__cleanup_sighand)
CL_MINE(it_real_fn)
CL_MINE(mmput)
CL_MINE(ns_capable)
CL_MINE(dec_ucount)
CL_MINE(proc_free_inum)
CL_MINE(__put_user_ns)
CL_MINE(__copy_io)
CL_MINE(exit_io_context)
CL_MINE(get_unused_fd_flags)
CL_MINE(pidfs_alloc_file)
CL_MINE(put_unused_fd)
CL_MINE(free_pid)

CL_MINE(task_join_group_stop)
CL_MINE(__ptrace_link)
CL_MINE(task_set_jobctl_pending)
CL_MINE(fd_install)
CL_MINE(tick_program_event)
CL_MINE(__fstate_save)
CL_MINE(__fstate_restore)
CL_MINE(wq_worker_running)
CL_MINE(io_wq_worker_running)
CL_MINE(of_clk_get)
CL_MINE(clk_put)
CL_MINE(disable_percpu_irq)
CL_MINE(tick_receive_broadcast)
CL_MINE(tick_broadcast_switch_to_oneshot)
CL_MINE(pm_power_off)

CL_MINE(perf_event_exit_cpu)
CL_MINE(smpcfd_dead_cpu)
CL_MINE(smpcfd_dying_cpu)
CL_MINE(tick_cpu_dying)
CL_MINE(smpboot_park_threads)
CL_MINE(lockup_detector_offline_cpu)
CL_MINE(touch_softlockup_watchdog)
CL_MINE(tick_broadcast_setup_oneshot)
CL_MINE(tick_broadcast_clear_oneshot)
CL_MINE(tick_broadcast)
CL_MINE(clock_was_set_delayed)
CL_MINE(second_overflow)
CL_MINE(tick_init_highres)
CL_MINE(tick_setup_sched_timer)

CL_MINE(resched_latency_warn)
CL_MINE(task_work_add)

CL_MINE(workqueue_set_max_active)
CL_MINE(bitmap_parse)
CL_MINE(device_unregister)
CL_MINE(destroy_workqueue)
CL_MINE(tmigr_handle_remote)
CL_MINE(do_futex)

CL_MINE(release_task)
CL_MINE(exit_ptrace)
CL_MINE(zap_pid_ns_processes)
CL_MINE(free_pipe_info)
CL_MINE(getrusage)

CL_MINE(schedule_hrtimeout)
CL_MINE(rt_mutex_setprio)
CL_MINE(io_wq_worker_sleeping)
CL_MINE(nmi_cpu_backtrace)
CL_MINE(irq_work_run)
CL_MINE(syscall_regfunc)
CL_MINE(syscall_unregfunc)
CL_MINE(__refrigerator)
CL_MINE(set_freezable)
CL_MINE(__kill_pgrp_info)
CL_MINE(blk_fill_rwbs)
CL_MINE(set_direct_map_invalid_noflush)
CL_MINE(set_direct_map_default_noflush)

CL_MINE(parameq)
CL_MINE(kernel_param_lock)
CL_MINE(kernel_param_unlock)
CL_MINE(security_locked_down)

CL_MINE(kobj_ns_type_registered)
CL_MINE(sysfs_remove_dir)
CL_MINE(pci_address_to_pio)
CL_MINE(amba_device_add)
CL_MINE(amba_device_alloc)
CL_MINE(amba_device_put)

CL_MINE(of_graph_get_remote_endpoint)
CL_MINE(of_graph_get_next_endpoint)
CL_MINE(of_property_read_variable_u16_array)
CL_MINE(of_property_read_variable_u64_array)
CL_MINE(of_property_read_variable_u8_array)
CL_MINE(of_device_get_match_data)

CL_MINE(trace_print_array_seq)

CL_MINE(set_secondary_fwnode)

CL_MINE(kernfs_put)

CL_MINE(driver_set_override)
CL_MINE(of_device_modalias)
CL_MINE(platform_pm_suspend)
CL_MINE(platform_pm_resume)
CL_MINE(pm_generic_runtime_suspend)
CL_MINE(pm_generic_runtime_resume)

CL_MINE(bus_find_device)
CL_MINE(bus_rescan_devices_helper)
CL_MINE(sysfs_streq)
CL_MINE(device_match_name)

CL_MINE(of_graph_get_remote_port_parent)
CL_MINE(of_graph_get_port_parent)

CL_MINE(pm_runtime_release_supplier)
CL_MINE(pm_runtime_drop_link)
CL_MINE(device_links_unbind_consumers)
CL_MINE(device_links_busy)
CL_MINE(device_links_driver_cleanup)

CL_MINE(device_links_force_bind)
CL_MINE(async_schedule_node)
CL_MINE(__dev_pm_qos_resume_latency)

CL_MINE(free_irq)
CL_MINE(irq_set_irq_wake)

CL_MINE(timer_reduce)
CL_MINE(rcu_cblist_init)
CL_MINE(flush_delayed_work)
CL_MINE(ktime_get_mono_fast_ns)
CL_MINE(autoremove_wake_function)
CL_MINE(prepare_to_wait)
CL_MINE(s2idle_wake)

CL_MINE(async_synchronize_full)
CL_MINE(class_for_each_device)
CL_MINE(device_pm_move_to_tail)

CL_MINE(irq_domain_translate_twocell)
CL_MINE(handle_edge_irq)

CL_MINE(pinmux_show_setting)
CL_MINE(pinctrl_dev_get_name)
CL_MINE(pinconf_show_setting)
CL_MINE(single_open)
CL_MINE(pinmux_show_map)
CL_MINE(pinconf_show_map)
CL_MINE(single_release)
CL_MINE(pinconf_free_setting)
CL_MINE(pinmux_free_setting)
CL_MINE(pinmux_disable_setting)
CL_MINE(pinmux_map_to_setting)
CL_MINE(pinconf_map_to_setting)
CL_MINE(get_pinctrl_dev_from_devname)
CL_MINE(pinmux_validate_map)
CL_MINE(pinconf_validate_map)
CL_MINE(device_match_of_node)

CL_MINE(of_pci_dma_range_parser_init)
CL_MINE(of_pci_range_parser_one)

CL_MINE(iommu_fwspec_init)
CL_MINE(iommu_ops_from_fwnode)
CL_MINE(driver_deferred_probe_check_state)
CL_MINE(of_map_id)
CL_MINE(pci_for_each_dma_alias)
CL_MINE(pci_request_acs)
CL_MINE(iommu_fwspec_free)
CL_MINE(dev_iommu_free)
CL_MINE(iommu_probe_device)

CL_MINE(pinmux_enable_setting)
CL_MINE(pinconf_apply_setting)

CL_MINE(dma_direct_need_sync)
CL_MINE(dma_direct_sync_sg_for_device)
CL_MINE(dma_direct_sync_sg_for_cpu)
CL_MINE(__swiotlb_sync_single_for_cpu)
CL_MINE(arch_sync_dma_for_cpu)
CL_MINE(__swiotlb_sync_single_for_device)
CL_MINE(arch_sync_dma_for_device)

CL_MINE(dma_unmap_page_attrs)
CL_MINE(dma_max_mapping_size)
CL_MINE(__sysfs_match_string)
CL_MINE(dma_alloc_attrs)
CL_MINE(dma_map_page_attrs)
CL_MINE(free_pages_exact)
CL_MINE(dma_free_attrs)

CL_MINE(prepare_to_wait_exclusive)
CL_MINE(io_schedule)
CL_MINE(lcm_not_zero)
CL_MINE(gcd)
CL_MINE(block_write_end)
CL_MINE(folio_unlock)
CL_MINE(block_write_begin)
CL_MINE(mpage_readahead)
CL_MINE(block_write_full_folio)
CL_MINE(write_cache_pages)
CL_MINE(fixed_size_llseek)
CL_MINE(generic_file_readonly_mmap)
CL_MINE(generic_file_mmap)
CL_MINE(iov_iter_is_aligned)

CL_MINE(kmem_cache_destroy)
CL_MINE(ioc_clear_queue)
CL_MINE(seq_list_next)
CL_MINE(seq_list_start)
CL_MINE(iov_iter_npages)
CL_MINE(copy_page_from_iter)
CL_MINE(kiocb_invalidate_pages)
CL_MINE(vfs_fsync_range)
CL_MINE(generic_atomic_write_valid)
CL_MINE(copy_page_to_iter)
CL_MINE(iomap_file_buffered_write)
CL_MINE(iov_iter_revert)
CL_MINE(direct_write_fallback)
CL_MINE(kiocb_invalidate_post_direct_write)
CL_MINE(filemap_read)
CL_MINE(kiocb_write_and_wait)
CL_MINE(iov_iter_advance)

CL_MINE(blkdev_issue_zeroout)
CL_MINE(blkdev_ioctl)
CL_MINE(compat_blkdev_ioctl)
CL_MINE(filemap_splice_read)
CL_MINE(blkdev_uring_cmd)
CL_MINE(block_dirty_folio)
CL_MINE(block_invalidate_folio)
CL_MINE(buffer_migrate_folio_norefs)
CL_MINE(buffer_check_dirty_writeback)
CL_MINE(iov_iter_extract_pages)
CL_MINE(unpin_user_page)
CL_MINE(iov_iter_alignment)
CL_MINE(iov_iter_gap_alignment)
CL_MINE(import_iovec)
CL_MINE(list_sort)

CL_MINE(wait_for_completion_io_timeout)
CL_MINE(wait_for_completion_io)
CL_MINE(truncate_inode_pages_final)
CL_MINE(invalidate_inode_buffers)
CL_MINE(folio_mark_dirty)
CL_MINE(security_bdev_free)
CL_MINE(__folio_lock)
CL_MINE(invalidate_bh_lrus)
CL_MINE(lru_add_drain_all)
CL_MINE(invalidate_mapping_pages)
CL_MINE(unpin_user_folio)
CL_MINE(do_writepages)

CL_MINE(may_open_dev)
CL_MINE(filemap_flush)
CL_MINE(truncate_inode_pages_range)
CL_MINE(invalidate_inode_pages2_range)
CL_MINE(truncate_inode_pages)
CL_MINE(write_inode_now)
CL_MINE(filemap_fdatawait_keep_errors)
CL_MINE(filemap_fdatawrite)
CL_MINE(_copy_to_user)
CL_MINE(wakeup_flusher_threads)
CL_MINE(proc_dointvec_jiffies)

CL_MINE(__cpuhp_state_remove_instance)
CL_MINE(laptop_io_completion)
CL_MINE(generic_fill_statx_atomic_writes)
CL_MINE(badblocks_store)
CL_MINE(class_dev_iter_next)
CL_MINE(class_dev_iter_exit)
CL_MINE(class_dev_iter_init)
CL_MINE(badblocks_show)

CL_MINE(drop_partition)
CL_MINE(device_del)
CL_MINE(kill_anon_super)
CL_MINE(jiffies_to_usecs)

CL_MINE(bdi_set_strict_limit)
CL_MINE(bdi_set_max_bytes)
CL_MINE(bdi_get_max_bytes)
CL_MINE(bdi_set_min_bytes)
CL_MINE(bdi_get_min_bytes)
CL_MINE(bdi_set_max_ratio_no_scale)
CL_MINE(bdi_set_max_ratio)
CL_MINE(bdi_set_min_ratio_no_scale)
CL_MINE(bdi_set_min_ratio)
CL_MINE(wb_update_bandwidth)
CL_MINE(wb_calc_thresh)
CL_MINE(debugfs_remove)
CL_MINE(wb_workfn)
CL_MINE(laptop_mode_timer_fn)

CL_MINE(file_update_time)
CL_MINE(touch_atime)
CL_MINE(clear_inode)
CL_MINE(proc_doulongvec_minmax)
CL_MINE(__remove_inode_hash)
CL_MINE(generic_delete_inode)

CL_MINE(security_sb_eat_lsm_opts)
CL_MINE(vfs_parse_fs_param_source)
CL_MINE(logfc)
CL_MINE(kmemdup_noprof)

CL_MINE(fc_drop_locked)

CL_MINE(super_trylock_shared)
CL_MINE(prune_dcache_sb)
CL_MINE(prune_icache_sb)
CL_MINE(shrinker_free)
CL_MINE(fsnotify_sb_free)
CL_MINE(security_sb_free)
CL_MINE(percpu_free_rwsem)
CL_MINE(put_super)
CL_MINE(deactivate_locked_super)

CL_MINE(mntns_operations)

CL_MINE(kill_litter_super)
CL_MINE(ramfs_init_fs_context)

CL_MINE(map_id_down)
CL_MINE(from_kgid)
CL_MINE(in_group_p)
CL_MINE(kmemdup_array)
CL_MINE(xattr_full_name)
CL_MINE(simple_xattr_set)
CL_MINE(simple_xattr_free)
CL_MINE(inode_maybe_inc_iversion)
CL_MINE(simple_xattr_space)
CL_MINE(simple_xattr_get)
CL_MINE(from_kgid_munged)
CL_MINE(simple_offset_destroy)
CL_MINE(ilookup5)
CL_MINE(d_find_alias)
CL_MINE(d_find_any_alias)
CL_MINE(fileattr_fill_flags)
CL_MINE(simple_xattr_add)
CL_MINE(simple_xattr_alloc)
CL_MINE(simple_xattrs_free)
CL_MINE(simple_xattr_list)

CL_MINE(generic_file_open)
CL_MINE(generic_write_checks)
CL_MINE(file_remove_privs)
CL_MINE(generic_perform_write)
CL_MINE(mapping_seek_hole_data)
CL_MINE(vfs_setpos)
CL_MINE(generic_file_llseek_size)
CL_MINE(mm_get_unmapped_area)
CL_MINE(inode_set_flags)
CL_MINE(init_special_inode)
CL_MINE(simple_offset_dir_operations)
CL_MINE(security_inode_init_security)
CL_MINE(simple_acl_create)
CL_MINE(d_tmpfile)
CL_MINE(finish_open)
CL_MINE(simple_offset_add)
CL_MINE(lru_note_cost_refault)
CL_MINE(nr_swap_pages)
CL_MINE(inode_add_lru)

CL_MINE(free_swap_and_cache_nr)
CL_MINE(inode_sub_bytes)
CL_MINE(generic_fillattr)
CL_MINE(inode_add_bytes)
CL_MINE(security_vm_enough_memory_mm)
CL_MINE(clear_nlink)
CL_MINE(alloc_file_pseudo)
CL_MINE(simple_offset_remove)
CL_MINE(drop_nlink)
CL_MINE(simple_empty)
CL_MINE(d_rehash)
CL_MINE(simple_offset_rename)
CL_MINE(simple_rename_timestamp)
CL_MINE(simple_offset_rename_exchange)
CL_MINE(total_swap_pages)
CL_MINE(folio_alloc_swap)

CL_MINE(add_to_swap_cache)
CL_MINE(swap_shmem_alloc)
CL_MINE(put_swap_folio)
CL_MINE(swap_writepage)
CL_MINE(get_swap_device)
CL_MINE(swap_cache_get_folio)
CL_MINE(swap_cluster_readahead)
CL_MINE(folio_wait_writeback)
CL_MINE(swapper_spaces)
CL_MINE(folio_copy)
CL_MINE(delete_from_swap_cache)
CL_MINE(swap_free_nr)
CL_MINE(filemap_remove_folio)
CL_MINE(iov_iter_zero)
CL_MINE(empty_zero_page)
CL_MINE(splice_folio_into_pipe)
CL_MINE(__folio_swap_cache_index)
CL_MINE(folio_wait_stable)
CL_MINE(free_unref_folios)

CL_MINE(find_lock_entries)
CL_MINE(folio_batch_remove_exceptionals)
CL_MINE(find_get_entries)
CL_MINE(truncate_inode_folio)
CL_MINE(__folio_batch_release)
CL_MINE(truncate_inode_partial_folio)
CL_MINE(folio_mapping)
CL_MINE(setattr_prepare)
CL_MINE(setattr_copy)
CL_MINE(posix_acl_chmod)
CL_MINE(unmap_mapping_range)
CL_MINE(file_modified)
CL_MINE(inode_newsize_ok)
CL_MINE(inode_nohighmem)
CL_MINE(filemap_get_folios)
CL_MINE(check_move_unevictable_folios)
CL_MINE(user_shm_unlock)
CL_MINE(user_shm_lock)
CL_MINE(noop_dirty_folio)

CL_MINE(migrate_folio)
CL_MINE(simple_set_acl)
CL_MINE(noop_fsync)
CL_MINE(filemap_map_pages)
CL_MINE(simple_get_link)

CL_MINE(__put_net)
CL_MINE(fsnotify)
CL_MINE(__fsnotify_inode_delete)
CL_MINE(device_pm_remove)
CL_MINE(dpm_sysfs_remove)
CL_MINE(reconfigure_single)

CL_MINE(__mark_inode_dirty)
CL_MINE(inode_io_list_del)
CL_MINE(inode_wait_for_writeback)
CL_MINE(__destroy_inode)
CL_MINE(cd_forget)

CL_MINE(__fsnotify_parent)
CL_MINE(locks_remove_file)
CL_MINE(security_file_release)
CL_MINE(file_f_owner_release)
CL_MINE(security_file_free)
CL_MINE(mnt_put_write_access)
CL_MINE(backing_file_user_path)
CL_MINE(cdev_put)
CL_MINE(eventpoll_release_file)
CL_MINE(dissolve_on_fput)

CL_MINE(__lookup_mnt)
CL_MINE(finish_automount)
CL_MINE(lookup_mnt)
CL_MINE(security_inode_follow_link)
CL_MINE(atime_needs_update)
CL_MINE(__audit_inode)
CL_MINE(audit_log_path_denied)
CL_MINE(__d_lookup)
CL_MINE(dget_parent)
CL_MINE(is_subdir)
CL_MINE(d_invalidate)
CL_MINE(__d_lookup_unhash_wake)
CL_MINE(fdget_raw)
CL_MINE(path_is_under)

CL_MINE(capable_wrt_inode_uidgid)
CL_MINE(get_cached_acl_rcu)
CL_MINE(posix_acl_permission)
CL_MINE(get_inode_acl)
CL_MINE(mnt_get_count)
CL_MINE(shrink_dentry_list)
CL_MINE(dput_to_list)
CL_MINE(__fsnotify_vfsmount_delete)
CL_MINE(mnt_pin_kill)
