#include <linux/printk.h>
#include "adaptor.h"

CL_MINE(get_random_bytes)
CL_MINE(__warn_printk)
CL_MINE(skip_spaces)
CL_MINE(__rcu_read_lock)
CL_MINE(__rcu_read_unlock)
CL_MINE(sprint_symbol)
CL_MINE(sprint_symbol_build_id)
CL_MINE(sprint_backtrace)
CL_MINE(sprint_symbol_no_offset)
CL_MINE(sprint_backtrace_build_id)
CL_MINE(string_escape_mem)
CL_MINE(fwnode_count_parents)
CL_MINE(fwnode_get_name_prefix)
CL_MINE(fwnode_get_name)

CL_MINE(fwnode_get_nth_parent)
CL_MINE(__clk_get_name)
CL_MINE(time64_to_tm)
CL_MINE(siphash_1u64)
CL_MINE(has_capability_noaudit)
CL_MINE(of_property_read_string)
CL_MINE(of_find_property)
CL_MINE(of_prop_next_string)
CL_MINE(errname)

CL_MINE(trace_event_buffer_reserve)
CL_MINE(trace_event_buffer_commit)
CL_MINE(trace_raw_output_prep)
CL_MINE(trace_event_printf)
CL_MINE(trace_handle_return)

CL_MINE(__trace_trigger_soft_disabled)
CL_MINE(perf_trace_buf_alloc)
CL_MINE(perf_trace_run_bpf_submit)

CL_MINE(memblock_mark_hotplug)

CL_MINE(ptlock_alloc)
CL_MINE(get_free_pages_noprof)
CL_MINE(_copy_from_user)

CL_MINE(print_tainted)
CL_MINE(get_taint)
CL_MINE(print_worker_info)
CL_MINE(print_stop_info)
CL_MINE(print_tainted_verbose)
CL_MINE(show_stack)

CL_MINE(bpf_trace_run1)
CL_MINE(bpf_trace_run2)
CL_MINE(bpf_trace_run3)
CL_MINE(bpf_trace_run4)
CL_MINE(bpf_trace_run5)
CL_MINE(bpf_trace_run6)
CL_MINE(bpf_trace_run10)
CL_MINE(trace_print_bitmask_seq)
CL_MINE(trace_print_flags_seq)
CL_MINE(trace_print_symbols_seq)
CL_MINE(preempt_schedule_notrace)
CL_MINE(__percpu_counter_sum)
CL_MINE(add_taint)

CL_MINE(preempt_schedule)
CL_MINE(__local_bh_enable_ip)
CL_MINE(queued_read_lock_slowpath)
CL_MINE(queued_write_lock_slowpath)
CL_MINE(__kernel_map_pages)
CL_MINE(execute_with_initialized_rng)

CL_MINE(kmem_cache_free)
CL_MINE(node_dirty_ok)
CL_MINE(wakeup_kswapd)

CL_MINE(decay_pcp_high)
CL_MINE(__seq_puts)
CL_MINE(seq_put_decimal_ull)
CL_MINE(seq_putc)
CL_MINE(seq_write)
CL_MINE(kfree)
CL_MINE(cancel_delayed_work_sync)
CL_MINE(round_jiffies_relative)
CL_MINE(queue_delayed_work_on)
CL_MINE(seq_open)
CL_MINE(housekeeping_test_cpu)
CL_MINE(__kmalloc_cache_noprof)
CL_MINE(global_dirty_limits)
CL_MINE(seq_printf)
CL_MINE(schedule_on_each_cpu)
CL_MINE(delayed_work_timer_fn)
CL_MINE(seq_lseek)
CL_MINE(seq_read)
CL_MINE(seq_release)
CL_MINE(alloc_workqueue)

CL_MINE(__kmalloc_node_noprof)
CL_MINE(__devm_add_action)
CL_MINE(trace_event_reg)
CL_MINE(trace_event_raw_init)

CL_MINE(wake_up_process)
CL_MINE(wake_q_add)
CL_MINE(wake_up_q)
CL_MINE(osq_lock)
CL_MINE(console_verbose)
CL_MINE(osq_unlock)
CL_MINE(schedule_preempt_disabled)
CL_MINE(io_schedule_prepare)
CL_MINE(io_schedule_finish)

CL_MINE(slab_is_available)
CL_MINE(pcpu_get_vm_areas)

CL_MINE(is_vmalloc_or_module_addr)
CL_MINE(new_vmalloc)
CL_MINE(__free_pages)
CL_MINE(vmap_pages_range_noflush)
CL_MINE(vunmap_range_noflush)
CL_MINE(flush_tlb_kernel_range)
CL_MINE(print_tracking)
CL_MINE(call_rcu)
CL_MINE(sysfs_slab_add)
CL_MINE(debugfs_slab_add)

CL_MINE(stack_trace_save)
CL_MINE(stack_depot_save)
CL_MINE(kmalloc_fix_flags)
CL_MINE(copy_from_kernel_nofault)
CL_MINE(gfp_pfmemalloc_allowed)

CL_MINE(cpu_maps_update_begin)
CL_MINE(cpu_maps_update_done)
CL_MINE(__percpu_down_read)
CL_MINE(rcuwait_wake_up)
CL_MINE(percpu_down_write)
CL_MINE(percpu_up_write)

CL_MINE(sysfs_emit)
CL_MINE(sysfs_emit_at)
CL_MINE(kmem_cache_shrink)
CL_MINE(slab_kmem_cache_release)
CL_MINE(sysfs_remove_link)
CL_MINE(sysfs_create_link)
CL_MINE(kobject_init_and_add)
CL_MINE(sysfs_create_group)
CL_MINE(kobject_del)
CL_MINE(queue_work_on)
CL_MINE(flush_work)
CL_MINE(validate_slab_cache)
CL_MINE(kobject_put)
CL_MINE(kset_create_and_add)
CL_MINE(warn_alloc)
CL_MINE(__kmalloc_cache_node_noprof)
CL_MINE(static_key_enable)
CL_MINE(stack_depot_init)
