#include <linux/printk.h>
#include "adaptor.h"

CL_MINE(xfrm6_local_error)
CL_MINE(xfrm6_transport_finish)
CL_MINE(xfrm6_output)

CL_MINE(laptop_sync_completion)
CL_MINE(thaw_super_locked)
CL_MINE(fs_context_for_reconfigure)
CL_MINE(group_pin_kill)
CL_MINE(sb_prepare_remount_readonly)

CL_MINE(ip6_find_1stfragopt)
CL_MINE(ipv6_select_ident)

CL_MINE(cmsghdr_from_user_compat_to_kern)
CL_MINE(get_compat_msghdr)

CL_MINE(dst_cache_init)
CL_MINE(dst_cache_destroy)
CL_MINE(dst_cache_reset_now)

CL_MINE(get_task_exe_file)
CL_MINE(simple_getattr)
CL_MINE(generic_file_write_iter)

CL_MINE(security_inet_csk_clone)
CL_MINE(reqsk_queue_alloc)
CL_MINE(security_req_classify_flow)

CL_MINE(replace_fd)
CL_MINE(file_open_root)
CL_MINE(arch_vma_name)
CL_MINE(__wake_up_sync)
CL_MINE(read_cache_page)
CL_MINE(vfs_fallocate)
CL_MINE(tcp_bpf_clone)
CL_MINE(mod_timer_pending)

CL_MINE(sprint_symbol_build_id)
CL_MINE(sprint_backtrace)
CL_MINE(sprint_symbol_no_offset)
CL_MINE(sprint_backtrace_build_id)
CL_MINE(audit_put_chunk)
CL_MINE(audit_tree_lookup)
CL_MINE(get_vfs_caps_from_disk)
CL_MINE(audit_watch_path)
CL_MINE(audit_tree_path)
CL_MINE(audit_mark_path)
CL_MINE(audit_classify_arch)
CL_MINE(audit_put_watch)
CL_MINE(audit_put_tree)
CL_MINE(audit_remove_mark)
CL_MINE(audit_alloc_mark)
CL_MINE(audit_make_tree)
CL_MINE(audit_to_watch)
CL_MINE(audit_get_watch)
CL_MINE(audit_dupe_exe)
CL_MINE(audit_remove_watch_rule)
CL_MINE(audit_remove_tree_rule)
CL_MINE(audit_remove_mark_rule)
CL_MINE(audit_add_watch)
CL_MINE(audit_add_tree_rule)
CL_MINE(audit_exe_compare)
CL_MINE(auditsc_get_stamp)
CL_MINE(audit_trim_trees)
CL_MINE(audit_tag_tree)

CL_MINE(wait_for_completion_killable_timeout)
CL_MINE(fs_umode_to_dtype)
CL_MINE(d_alloc_cursor)

CL_MINE(page_symlink)
CL_MINE(simple_link)
CL_MINE(simple_unlink)
CL_MINE(simple_rmdir)
CL_MINE(simple_rename)

CL_MINE(fsnotify_put_group)
CL_MINE(fsnotify_get_group)
CL_MINE(fsnotify_set_children_dentry_flags)

CL_MINE(__clk_get_name)
CL_MINE(time64_to_tm)
CL_MINE(has_capability_noaudit)
CL_MINE(errname)

CL_MINE(trace_event_buffer_reserve)
CL_MINE(trace_event_buffer_commit)
CL_MINE(trace_raw_output_prep)
CL_MINE(trace_event_printf)
CL_MINE(trace_handle_return)

CL_MINE(__trace_trigger_soft_disabled)
CL_MINE(perf_trace_buf_alloc)

CL_MINE(memblock_mark_hotplug)

CL_MINE(print_worker_info)
CL_MINE(rmap_walk)
CL_MINE(page_vma_mapped_walk)
CL_MINE(release_pages)
CL_MINE(__mmu_notifier_invalidate_range_start)
CL_MINE(__mmu_notifier_invalidate_range_end)

CL_MINE(trace_print_bitmask_seq)
CL_MINE(trace_print_flags_seq)
CL_MINE(trace_print_symbols_seq)
CL_MINE(add_taint)

CL_MINE(__kernel_map_pages)

CL_MINE(wakeup_kswapd)

CL_MINE(decay_pcp_high)
CL_MINE(round_jiffies_relative)

CL_MINE(trace_event_reg)
CL_MINE(trace_event_raw_init)

CL_MINE(pcpu_get_vm_areas)

CL_MINE(print_tracking)
CL_MINE(sysfs_slab_add)
CL_MINE(debugfs_slab_add)

CL_MINE(stack_trace_save)
CL_MINE(stack_depot_save)
CL_MINE(kmalloc_fix_flags)
CL_MINE(gfp_pfmemalloc_allowed)

CL_MINE(sysfs_emit)
CL_MINE(sysfs_emit_at)
CL_MINE(kmem_cache_shrink)
CL_MINE(slab_kmem_cache_release)
CL_MINE(kobject_del)
CL_MINE(warn_alloc)
CL_MINE(stack_depot_init)

CL_MINE(purge_fragmented_blocks_allcpus)

CL_MINE(do_trap_load_misaligned)

CL_MINE(show_ipi_stats)

CL_MINE(irq_free_descs)

CL_MINE(nr_context_switches_cpu)

CL_MINE(schedule_timeout_idle)
CL_MINE(tracing_off)
CL_MINE(ftrace_dump)
CL_MINE(resched_cpu)
CL_MINE(kthread_flush_work)

CL_MINE(irq_work_queue_on)
CL_MINE(rcu_segcblist_first_pend_cb)
CL_MINE(nbcon_cpu_emergency_enter)
CL_MINE(nbcon_cpu_emergency_exit)
CL_MINE(sched_show_task)
CL_MINE(dump_cpu_task)

CL_MINE(rcu_segcblist_merge)
CL_MINE(rcu_segcblist_disable)
CL_MINE(rcu_segcblist_first_cb)
CL_MINE(nr_context_switches)

CL_MINE(kmem_dump_obj)
CL_MINE(task_call_func)
CL_MINE(bitmap_parselist)
CL_MINE(cancel_work_sync)
CL_MINE(irq_domain_deactivate_irq)

CL_MINE(irq_work_queue)
CL_MINE(housekeeping_affine)
CL_MINE(idle_task)
CL_MINE(cpu_curr_snapshot)
CL_MINE(sifive_errata_patch_func)
CL_MINE(thead_errata_patch_func)

CL_MINE(riscv_get_mvendorid)
CL_MINE(riscv_get_marchid)
CL_MINE(irq_disable)
CL_MINE(proc_dointvec_minmax)
CL_MINE(proc_douintvec)

CL_MINE(uprobe_single_step_handler)
CL_MINE(uprobe_breakpoint_handler)
CL_MINE(do_mseal)

CL_MINE(cpudl_cleanup)
CL_MINE(housekeeping_any_cpu)

CL_MINE(call_trace_sched_update_nr_running)
CL_MINE(cpuidle_find_deepest_state)
CL_MINE(cpuidle_enter)
CL_MINE(cpuhp_report_idle_dead)
CL_MINE(cpuidle_select)
CL_MINE(tick_nohz_tick_stopped)
CL_MINE(cpuidle_reflect)
CL_MINE(cpuidle_enter_s2idle)
CL_MINE(tick_nohz_idle_retain_tick)

CL_MINE(cpuidle_use_deepest_state)
CL_MINE(proc_dointvec)
CL_MINE(cpupri_find)

CL_MINE(cpupri_find_fitness)
CL_MINE(double_rq_lock)
CL_MINE(plist_del)
CL_MINE(plist_add)
CL_MINE(sched_get_rd)
CL_MINE(sched_put_rd)

CL_MINE(partition_sched_domains)
CL_MINE(init_wait_var_entry)

CL_MINE(trace_output_call)
CL_MINE(print_cfs_rq)
CL_MINE(print_rt_rq)

CL_MINE(hrtimer_forward)
CL_MINE(print_dl_rq)
CL_MINE(proc_douintvec_minmax)
CL_MINE(cpupri_cleanup)
CL_MINE(profile_hits)

CL_MINE(freezing_slow_path)
CL_MINE(force_sig)
CL_MINE(proc_dobool)

CL_MINE(fasync_helper)
CL_MINE(argv_split)
CL_MINE(argv_free)
CL_MINE(kill_pid)

CL_MINE(proc_dostring)

CL_MINE(noop_llseek)
CL_MINE(compat_ptr_ioctl)
CL_MINE(trace_define_field)
CL_MINE(syscall_exit_register)
CL_MINE(syscall_enter_register)

CL_MINE(create_user_ns)
CL_MINE(install_thread_keyring_to_cred)
CL_MINE(sched_cancel_fork)
CL_MINE(__audit_free)
CL_MINE(stashed_dentry_prune)
CL_MINE(copy_tree)

CL_MINE(thread_group_sample_cputime)
CL_MINE(set_memory_ro)
CL_MINE(dec_ucount)
CL_MINE(__put_user_ns)
CL_MINE(__copy_io)
CL_MINE(exit_io_context)
CL_MINE(pidfs_alloc_file)

CL_MINE(__mmu_notifier_release)


CL_MINE(task_join_group_stop)
CL_MINE(task_set_jobctl_pending)
CL_MINE(tick_program_event)
CL_MINE(io_wq_worker_running)
CL_MINE(of_clk_get)
CL_MINE(clk_put)
CL_MINE(disable_percpu_irq)
CL_MINE(tick_receive_broadcast)
CL_MINE(tick_broadcast_switch_to_oneshot)

CL_MINE(smpcfd_dead_cpu)
CL_MINE(smpcfd_dying_cpu)
CL_MINE(tick_cpu_dying)
CL_MINE(smpboot_park_threads)
CL_MINE(lockup_detector_offline_cpu)
CL_MINE(touch_softlockup_watchdog)
CL_MINE(tick_broadcast_setup_oneshot)
CL_MINE(tick_broadcast_clear_oneshot)
CL_MINE(tick_broadcast)
CL_MINE(clock_was_set_delayed)
CL_MINE(tick_init_highres)
CL_MINE(tick_setup_sched_timer)

CL_MINE(resched_latency_warn)

CL_MINE(workqueue_set_max_active)
CL_MINE(bitmap_parse)
CL_MINE(device_unregister)
CL_MINE(tmigr_handle_remote)
CL_MINE(do_futex)

CL_MINE(zap_pid_ns_processes)
CL_MINE(getrusage)

CL_MINE(send_sig)
CL_MINE(__audit_fd_pair)
CL_MINE(do_proc_douintvec)

CL_MINE(rt_mutex_setprio)
CL_MINE(io_wq_worker_sleeping)
CL_MINE(nmi_cpu_backtrace)
CL_MINE(irq_work_run)
CL_MINE(syscall_regfunc)
CL_MINE(syscall_unregfunc)
CL_MINE(__refrigerator)
CL_MINE(__kill_pgrp_info)
CL_MINE(blk_fill_rwbs)
CL_MINE(set_direct_map_invalid_noflush)
CL_MINE(set_direct_map_default_noflush)

CL_MINE(kernel_param_lock)
CL_MINE(kernel_param_unlock)
CL_MINE(security_locked_down)

CL_MINE(kobj_ns_type_registered)
CL_MINE(sysfs_remove_dir)
CL_MINE(pci_address_to_pio)
CL_MINE(amba_device_add)
CL_MINE(amba_device_alloc)
CL_MINE(amba_device_put)

CL_MINE(of_graph_get_remote_endpoint)
CL_MINE(of_graph_get_next_endpoint)
CL_MINE(of_property_read_variable_u16_array)
CL_MINE(of_property_read_variable_u64_array)
CL_MINE(of_property_read_variable_u8_array)
CL_MINE(of_device_get_match_data)

CL_MINE(trace_print_array_seq)

CL_MINE(set_secondary_fwnode)

CL_MINE(kernfs_put)

CL_MINE(driver_set_override)
CL_MINE(of_device_modalias)
CL_MINE(platform_pm_suspend)
CL_MINE(platform_pm_resume)
CL_MINE(pm_generic_runtime_suspend)
CL_MINE(pm_generic_runtime_resume)

CL_MINE(bus_find_device)
CL_MINE(bus_rescan_devices_helper)
CL_MINE(sysfs_streq)
CL_MINE(device_match_name)

CL_MINE(of_graph_get_remote_port_parent)
CL_MINE(of_graph_get_port_parent)

CL_MINE(pm_runtime_release_supplier)
CL_MINE(pm_runtime_drop_link)
CL_MINE(device_links_unbind_consumers)
CL_MINE(device_links_busy)
CL_MINE(device_links_driver_cleanup)

CL_MINE(device_links_force_bind)
CL_MINE(__dev_pm_qos_resume_latency)

CL_MINE(free_irq)
CL_MINE(irq_set_irq_wake)

CL_MINE(timer_reduce)
CL_MINE(rcu_cblist_init)
CL_MINE(flush_delayed_work)
CL_MINE(s2idle_wake)

CL_MINE(class_for_each_device)
CL_MINE(device_pm_move_to_tail)

CL_MINE(irq_domain_translate_twocell)
CL_MINE(handle_edge_irq)

CL_MINE(pinmux_show_setting)
CL_MINE(pinctrl_dev_get_name)
CL_MINE(pinconf_show_setting)
CL_MINE(pinmux_show_map)
CL_MINE(pinconf_show_map)
CL_MINE(pinconf_free_setting)
CL_MINE(pinmux_free_setting)
CL_MINE(pinmux_disable_setting)
CL_MINE(pinmux_map_to_setting)
CL_MINE(pinconf_map_to_setting)
CL_MINE(get_pinctrl_dev_from_devname)
CL_MINE(pinmux_validate_map)
CL_MINE(pinconf_validate_map)
CL_MINE(device_match_of_node)

CL_MINE(of_pci_dma_range_parser_init)
CL_MINE(of_pci_range_parser_one)

CL_MINE(iommu_fwspec_init)
CL_MINE(iommu_ops_from_fwnode)
CL_MINE(driver_deferred_probe_check_state)
CL_MINE(of_map_id)
CL_MINE(pci_for_each_dma_alias)
CL_MINE(pci_request_acs)
CL_MINE(iommu_fwspec_free)
CL_MINE(dev_iommu_free)
CL_MINE(iommu_probe_device)

CL_MINE(pinmux_enable_setting)
CL_MINE(pinconf_apply_setting)

CL_MINE(dma_direct_need_sync)
CL_MINE(dma_direct_sync_sg_for_device)
CL_MINE(dma_direct_sync_sg_for_cpu)
CL_MINE(__swiotlb_sync_single_for_cpu)
CL_MINE(arch_sync_dma_for_cpu)
CL_MINE(__swiotlb_sync_single_for_device)
CL_MINE(arch_sync_dma_for_device)

CL_MINE(dma_unmap_page_attrs)
CL_MINE(dma_max_mapping_size)
CL_MINE(__sysfs_match_string)
CL_MINE(dma_alloc_attrs)
CL_MINE(dma_map_page_attrs)
CL_MINE(dma_free_attrs)

CL_MINE(lcm_not_zero)
CL_MINE(gcd)
CL_MINE(block_write_begin)
CL_MINE(fixed_size_llseek)
CL_MINE(folio_redirty_for_writepage)
CL_MINE(__acct_reclaim_writeback)

CL_MINE(kiocb_invalidate_pages)
CL_MINE(generic_atomic_write_valid)
CL_MINE(direct_write_fallback)
CL_MINE(kiocb_invalidate_post_direct_write)
CL_MINE(kiocb_write_and_wait)
CL_MINE(page_cache_prev_miss)

CL_MINE(kernel_vector_begin)
CL_MINE(__asm_vector_usercopy)
CL_MINE(kernel_vector_end)

CL_MINE(blkdev_issue_zeroout)
CL_MINE(blkdev_ioctl)
CL_MINE(compat_blkdev_ioctl)
CL_MINE(blkdev_uring_cmd)
CL_MINE(block_dirty_folio)
CL_MINE(buffer_migrate_folio_norefs)
CL_MINE(buffer_check_dirty_writeback)
CL_MINE(list_sort)
CL_MINE(need_mlock_drain)
CL_MINE(invalidate_bh_lrus_cpu)

CL_MINE(wait_for_completion_io)
CL_MINE(folio_mark_dirty)
CL_MINE(security_bdev_free)
CL_MINE(__folio_lock)
CL_MINE(reclaim_throttle)
CL_MINE(__filemap_set_wb_err)
CL_MINE(remove_mapping)

CL_MINE(invalidate_inode_pages2_range)
CL_MINE(proc_dointvec_jiffies)

CL_MINE(__cpuhp_state_remove_instance)
CL_MINE(laptop_io_completion)
CL_MINE(generic_fill_statx_atomic_writes)
CL_MINE(badblocks_store)
CL_MINE(badblocks_show)

CL_MINE(drop_partition)
CL_MINE(device_del)
CL_MINE(kill_anon_super)

CL_MINE(bdi_set_strict_limit)
CL_MINE(bdi_set_max_bytes)
CL_MINE(bdi_get_max_bytes)
CL_MINE(bdi_set_min_bytes)
CL_MINE(bdi_get_min_bytes)
CL_MINE(bdi_set_max_ratio_no_scale)
CL_MINE(bdi_set_max_ratio)
CL_MINE(bdi_set_min_ratio_no_scale)
CL_MINE(bdi_set_min_ratio)
CL_MINE(wb_calc_thresh)
CL_MINE(debugfs_remove)
CL_MINE(laptop_mode_timer_fn)

CL_MINE(proc_doulongvec_minmax)


CL_MINE(fc_drop_locked)

CL_MINE(prune_dcache_sb)
CL_MINE(prune_icache_sb)

CL_MINE(kill_litter_super)

CL_MINE(in_group_p)
CL_MINE(kmemdup_array)
CL_MINE(xattr_full_name)
CL_MINE(simple_xattr_set)
CL_MINE(simple_xattr_free)
CL_MINE(simple_xattr_space)
CL_MINE(simple_xattr_get)
CL_MINE(simple_offset_destroy)
CL_MINE(ilookup5)
CL_MINE(fileattr_fill_flags)
CL_MINE(simple_xattr_add)
CL_MINE(simple_xattr_alloc)
CL_MINE(simple_xattrs_free)
CL_MINE(simple_xattr_list)

CL_MINE(file_remove_privs)
CL_MINE(mm_get_unmapped_area)
CL_MINE(lru_note_cost_refault)
CL_MINE(vfs_path_lookup)

CL_MINE(free_swap_and_cache_nr)
CL_MINE(simple_offset_remove)
CL_MINE(simple_empty)
CL_MINE(d_rehash)
CL_MINE(simple_offset_rename)
CL_MINE(simple_rename_timestamp)
CL_MINE(simple_offset_rename_exchange)
CL_MINE(folio_alloc_swap)

CL_MINE(add_to_swap_cache)
CL_MINE(swap_shmem_alloc)
CL_MINE(put_swap_folio)
CL_MINE(swap_writepage)
CL_MINE(get_swap_device)
CL_MINE(swap_cache_get_folio)
CL_MINE(swap_cluster_readahead)
CL_MINE(folio_copy)
CL_MINE(delete_from_swap_cache)
CL_MINE(swap_free_nr)
CL_MINE(__folio_swap_cache_index)

CL_MINE(posix_acl_chmod)
CL_MINE(inode_nohighmem)
CL_MINE(check_move_unevictable_folios)
CL_MINE(user_shm_unlock)
CL_MINE(user_shm_lock)
CL_MINE(noop_dirty_folio)

CL_MINE(migrate_folio)
CL_MINE(simple_set_acl)
CL_MINE(simple_get_link)

CL_MINE(fsnotify)
CL_MINE(device_pm_remove)
CL_MINE(dpm_sysfs_remove)
CL_MINE(reconfigure_single)

CL_MINE(__fsnotify_parent)
CL_MINE(backing_file_user_path)
CL_MINE(eventpoll_release_file)

CL_MINE(finish_automount)
CL_MINE(path_is_under)

CL_MINE(capable_wrt_inode_uidgid)
CL_MINE(get_cached_acl_rcu)
CL_MINE(posix_acl_permission)
CL_MINE(mnt_get_count)
CL_MINE(__fsnotify_vfsmount_delete)
CL_MINE(mnt_pin_kill)

CL_MINE(generic_file_llseek)

CL_MINE(filemap_dirty_folio)
CL_MINE(pagecache_isize_extended)
CL_MINE(truncate_pagecache_range)

CL_MINE(clean_bdev_aliases)
CL_MINE(folio_zero_new_buffers)

CL_MINE(write_dirty_buffer)
CL_MINE(posix_acl_alloc)
CL_MINE(posix_acl_update_mode)
CL_MINE(d_obtain_alias)
CL_MINE(__bforget)
CL_MINE(sysfs_notify)

CL_MINE(mb_cache_entry_create)
CL_MINE(sync_dirty_buffer)
CL_MINE(blkdev_issue_discard)
CL_MINE(mb_cache_entry_delete_or_get)
CL_MINE(mb_cache_entry_wait_unused)
CL_MINE(__mb_cache_entry_free)
CL_MINE(mb_cache_entry_get)
CL_MINE(mb_cache_entry_find_first)
CL_MINE(mb_cache_entry_find_next)
CL_MINE(mb_cache_entry_touch)

CL_MINE(block_commit_write)
CL_MINE(mb_cache_destroy)
CL_MINE(mnt_want_write_file)
CL_MINE(mnt_drop_write_file)
CL_MINE(generic_buffers_fsync_noflush)
CL_MINE(inode_owner_or_capable)
CL_MINE(sync_mapping_buffers)
CL_MINE(iomap_swapfile_activate)
CL_MINE(sync_inode_metadata)

CL_MINE(d_mark_dontcache)
CL_MINE(iomap_seek_data)
CL_MINE(iomap_seek_hole)
CL_MINE(iomap_dio_rw)
CL_MINE(mark_buffer_dirty_inode)
CL_MINE(inode_needs_sync)
CL_MINE(find_inode_by_ino_rcu)
CL_MINE(memweight)
CL_MINE(generic_read_dir)
CL_MINE(nop_posix_acl_access)

CL_MINE(nop_posix_acl_default)
CL_MINE(fiemap_prep)
CL_MINE(fiemap_fill_next_extent)
CL_MINE(block_page_mkwrite)
CL_MINE(generic_fh_to_parent)
CL_MINE(generic_fh_to_dentry)
CL_MINE(nsecs_to_jiffies)
CL_MINE(crc16)
CL_MINE(__bread_gfp)
CL_MINE(block_is_partially_uptodate)
CL_MINE(generic_error_remove_folio)

CL_MINE(buffer_migrate_folio)
CL_MINE(kstrndup)
CL_MINE(generic_encode_ino32_fh)

CL_MINE(nfs_root_data)
CL_MINE(__audit_inode_child)

CL_MINE(__break_lease)

CL_MINE(mnt_change_mountpoint)

CL_MINE(driver_probe_done)
CL_MINE(ksys_unshare)
CL_MINE(kern_path_locked)

CL_MINE(__is_local_mountpoint)
CL_MINE(__detach_mounts)

CL_MINE(evict_inodes)
CL_MINE(fsnotify_sb_delete)
CL_MINE(security_sb_delete)

CL_MINE(queue_work_node)
CL_MINE(workqueue_set_min_active)
CL_MINE(try_wait_for_completion)

CL_MINE(unmap_mapping_folio)

CL_MINE(shrink_dcache_sb)
CL_MINE(invalidate_inodes)
CL_MINE(thaw_super)
CL_MINE(freeze_super)


CL_MINE(smp_call_function)

CL_MINE(vma_needs_dirty_tracking)
CL_MINE(folio_isolate_lru)
CL_MINE(alloc_migration_target)
CL_MINE(migrate_pages)
CL_MINE(putback_movable_pages)
CL_MINE(filemap_get_folios_contig)

CL_MINE(schedule_timeout_killable)
CL_MINE(hugetlb_file_setup)

CL_MINE(futex_cmpxchg_value_locked)
CL_MINE(fault_in_user_writeable)
CL_MINE(futex_wake)
CL_MINE(futex_hash)
CL_MINE(rt_mutex_futex_unlock)
CL_MINE(put_pi_state)

CL_MINE(elf_core_dump)
CL_MINE(privileged_wrt_inode_uidgid)

CL_MINE(smp_call_function_many)
CL_MINE(exchange_tids)
CL_MINE(transfer_pid)

CL_MINE(copy_mnt_ns)
CL_MINE(copy_utsname)
CL_MINE(copy_ipcs)
CL_MINE(copy_pid_ns)
CL_MINE(copy_time_ns)
CL_MINE(timens_on_fork)
CL_MINE(free_uts_ns)
CL_MINE(put_ipc_ns)
CL_MINE(sysctl_legacy_va_layout)

CL_MINE(vm_normal_folio)

CL_MINE(do_munmap)

CL_MINE(pagefault_out_of_memory)
CL_MINE(find_timens_vvar_page)
CL_MINE(vmf_insert_pfn)
CL_MINE(futex_exit_recursive)

CL_MINE(do_no_restart_syscall)
CL_MINE(__rseq_handle_notify_resume)
CL_MINE(compat_setup_rt_frame)
CL_MINE(get_cpu_vector_context)
CL_MINE(put_cpu_vector_context)
CL_MINE(do_swap_page)
CL_MINE(__secure_computing)

/* Missing syscall wrappers referenced by arch/riscv/kernel/syscall_table.c. */
CL_MINE(__riscv_sys_chroot)
CL_MINE(__riscv_sys_clock_getres)
CL_MINE(__riscv_sys_clock_nanosleep)
CL_MINE(__riscv_sys_clone3)
CL_MINE(__riscv_sys_close_range)
CL_MINE(__riscv_sys_exit)
CL_MINE(__riscv_compat_sys_execve)
CL_MINE(__riscv_sys_faccessat2)
CL_MINE(__riscv_sys_fallocate)
CL_MINE(__riscv_sys_fchdir)
CL_MINE(__riscv_sys_fchmodat)
CL_MINE(__riscv_sys_fchmodat2)
CL_MINE(__riscv_sys_fgetxattr)
CL_MINE(__riscv_sys_flistxattr)
CL_MINE(__riscv_sys_fremovexattr)
CL_MINE(__riscv_sys_fsconfig)
CL_MINE(__riscv_sys_fsetxattr)
CL_MINE(__riscv_sys_fsmount)
CL_MINE(__riscv_sys_fsopen)
CL_MINE(__riscv_sys_fspick)
CL_MINE(__riscv_sys_getcpu)
CL_MINE(__riscv_sys_getpgid)
CL_MINE(__riscv_sys_getpriority)
CL_MINE(__riscv_sys_getrlimit)
CL_MINE(__riscv_sys_getrusage)
CL_MINE(__riscv_sys_getsid)
CL_MINE(__riscv_sys_gettid)
CL_MINE(__riscv_sys_getxattr)
CL_MINE(__riscv_sys_lgetxattr)
CL_MINE(__riscv_sys_listmount)
CL_MINE(__riscv_sys_listxattr)
CL_MINE(__riscv_sys_llistxattr)
CL_MINE(__riscv_sys_lremovexattr)
CL_MINE(__riscv_sys_lsetxattr)
CL_MINE(__riscv_sys_mknodat)
CL_MINE(__riscv_sys_mount_setattr)
CL_MINE(__riscv_sys_move_mount)
CL_MINE(__riscv_sys_open_tree)
CL_MINE(__riscv_sys_openat2)
CL_MINE(__riscv_sys_personality)
CL_MINE(__riscv_sys_pidfd_getfd)
CL_MINE(__riscv_sys_pidfd_open)
CL_MINE(__riscv_sys_pidfd_send_signal)
CL_MINE(__riscv_sys_pivot_root)
CL_MINE(__riscv_sys_prctl)
CL_MINE(__riscv_sys_pread64)
CL_MINE(__riscv_sys_preadv)
CL_MINE(__riscv_sys_preadv2)
CL_MINE(__riscv_sys_prlimit64)
CL_MINE(__riscv_sys_pwrite64)
CL_MINE(__riscv_sys_pwritev)
CL_MINE(__riscv_sys_pwritev2)
CL_MINE(__riscv_sys_readahead)
CL_MINE(__riscv_sys_removexattr)
CL_MINE(__riscv_sys_restart_syscall)
CL_MINE(__riscv_sys_rt_sigpending)
CL_MINE(__riscv_sys_rt_sigqueueinfo)
CL_MINE(__riscv_sys_rt_sigsuspend)
CL_MINE(__riscv_sys_rt_tgsigqueueinfo)
CL_MINE(__riscv_sys_sched_get_priority_max)
CL_MINE(__riscv_sys_sched_get_priority_min)
CL_MINE(__riscv_sys_sched_getaffinity)
CL_MINE(__riscv_sys_sched_getattr)
CL_MINE(__riscv_sys_sched_getparam)
CL_MINE(__riscv_sys_sched_getscheduler)
CL_MINE(__riscv_sys_sched_rr_get_interval)
CL_MINE(__riscv_sys_sched_setaffinity)
CL_MINE(__riscv_sys_sched_setattr)
CL_MINE(__riscv_sys_sched_setparam)
CL_MINE(__riscv_sys_sched_setscheduler)
CL_MINE(__riscv_sys_sched_yield)
CL_MINE(__riscv_sys_setdomainname)
CL_MINE(__riscv_sys_sethostname)
CL_MINE(__riscv_sys_setns)
CL_MINE(__riscv_sys_setpgid)
CL_MINE(__riscv_sys_setpriority)
CL_MINE(__riscv_sys_setrlimit)
CL_MINE(__riscv_sys_setxattr)
CL_MINE(__riscv_sys_sigaltstack)
CL_MINE(__riscv_sys_statmount)
CL_MINE(__riscv_sys_statx)
CL_MINE(__riscv_sys_sysinfo)
CL_MINE(__riscv_sys_tgkill)
CL_MINE(__riscv_sys_times)
CL_MINE(__riscv_sys_tkill)
CL_MINE(__riscv_sys_truncate)
CL_MINE(__riscv_sys_umount)
CL_MINE(__riscv_sys_unshare)
CL_MINE(__riscv_sys_vhangup)
CL_MINE(__riscv_sys_waitid)

CL_MINE(f_delown)

/* Missing compat syscall wrappers referenced by arch/riscv/kernel/compat_syscall_table.c. */
CL_MINE(__riscv_compat_sys_execveat)
CL_MINE(__riscv_compat_sys_fallocate)
CL_MINE(__riscv_compat_sys_fcntl64)
CL_MINE(__riscv_compat_sys_ftruncate64)
CL_MINE(__riscv_compat_sys_getrusage)
CL_MINE(__riscv_compat_sys_ioctl)
CL_MINE(__riscv_compat_sys_ppoll_time64)
CL_MINE(__riscv_compat_sys_pread64)
CL_MINE(__riscv_compat_sys_preadv)
CL_MINE(__riscv_compat_sys_preadv2)
CL_MINE(__riscv_compat_sys_pselect6_time64)
CL_MINE(__riscv_compat_sys_pwrite64)
CL_MINE(__riscv_compat_sys_pwritev)
CL_MINE(__riscv_compat_sys_pwritev2)
CL_MINE(__riscv_compat_sys_readahead)
CL_MINE(__riscv_compat_sys_rt_sigpending)
CL_MINE(__riscv_compat_sys_rt_sigprocmask)
CL_MINE(__riscv_compat_sys_rt_sigqueueinfo)
CL_MINE(__riscv_compat_sys_rt_sigreturn)
CL_MINE(__riscv_compat_sys_rt_sigsuspend)
CL_MINE(__riscv_compat_sys_rt_sigtimedwait_time64)
CL_MINE(__riscv_compat_sys_rt_tgsigqueueinfo)
CL_MINE(__riscv_compat_sys_sigaltstack)
CL_MINE(__riscv_compat_sys_sysinfo)
CL_MINE(__riscv_compat_sys_times)
CL_MINE(__riscv_compat_sys_truncate64)
CL_MINE(__riscv_compat_sys_waitid)

/* Additional native wrappers pulled in by compat_sys_call_table. */
CL_MINE(__riscv_sys_llseek)

/* Additional native functions referenced by mmap.c and hugetlb.c. */
CL_MINE(copy_user_large_folio)
CL_MINE(hugetlb_add_new_anon_rmap)
CL_MINE(folio_zero_user)
CL_MINE(migration_entry_wait_huge)
CL_MINE(adjust_managed_page_count)
CL_MINE(memblock_reserved_mark_noinit)
CL_MINE(sysfs_remove_group)
CL_MINE(apply_workqueue_attrs)
CL_MINE(__cpuhp_remove_state)

/* Additional native functions referenced by kernel/sched/debug.c. */
CL_MINE(match_string)
CL_MINE(debugfs_lookup_and_remove)
CL_MINE(debugfs_create_ulong)
CL_MINE(debugfs_create_u64)
CL_MINE(debugfs_create_str)
CL_MINE(debugfs_write_file_bool)
CL_MINE(default_llseek)
CL_MINE(debugfs_read_file_bool)
CL_MINE(simple_open)

CL_MINE(__get_task_comm)

/* Additional native functions referenced by fs/select.c and time helpers. */
CL_MINE(add_swap_count_continuation)
CL_MINE(swap_duplicate)
CL_MINE(do_timens_ktime_to_host)
CL_MINE(ktime_get_coarse_ts64)
CL_MINE(ktime_get_raw_ts64)
CL_MINE(common_timer_set)
CL_MINE(common_timer_del)
CL_MINE(common_timer_get)
CL_MINE(posix_timer_queue_signal)
CL_MINE(platform_device_register_full)
CL_MINE(device_set_wakeup_capable)
CL_MINE(device_wakeup_enable)
CL_MINE(platform_device_unregister)
CL_MINE(rtc_timer_cancel)
CL_MINE(nanosleep_copyout)
CL_MINE(rtc_read_time)
CL_MINE(rtc_tm_to_ktime)
CL_MINE(rtc_timer_start)
CL_MINE(pm_wakeup_dev_event)
CL_MINE(task_sched_runtime)
CL_MINE(class_interface_unregister)
CL_MINE(posix_timer_set_common)
CL_MINE(posix_cpu_timer_rearm)
CL_MINE(rtc_irq_set_state)
CL_MINE(rtc_read_alarm)
CL_MINE(rtc_set_time)
CL_MINE(rtc_set_offset)
CL_MINE(rtc_irq_set_freq)
CL_MINE(rtc_update_irq_enable)
CL_MINE(rtc_alarm_irq_enable)
CL_MINE(rtc_tm_to_time64)
CL_MINE(rtc_valid_tm)
CL_MINE(rtc_set_alarm)
CL_MINE(rtc_read_offset)
CL_MINE(rtc_time64_to_tm)
CL_MINE(exit_oom_victim)
CL_MINE(do_adjtimex)
CL_MINE(tty_name)
CL_MINE(tty_audit_push)

/* Additional native functions referenced by net/core/skbuff.c. */
CL_MINE(__page_frag_alloc_align)
CL_MINE(net_ratelimit)
CL_MINE(file_ns_capable)
CL_MINE(crypto_ahash_update)
CL_MINE(__sock_gen_cookie)
CL_MINE(trace_print_hex_seq)
CL_MINE(pidfd_prepare)
CL_MINE(security_sk_clone)
CL_MINE(security_socket_getpeersec_stream)
CL_MINE(send_sigurg)
CL_MINE(sock_diag_broadcast_destroy)
CL_MINE(nf_queue)
CL_MINE(unregister_net_sysctl_table)
CL_MINE(nf_queue_nf_hook_drop)
CL_MINE(key_remove_domain)
CL_MINE(proc_ns_file)
CL_MINE(usleep_range_state)
CL_MINE(netdev_stat_queue_sum)
CL_MINE(net_dim_work_cancel)
CL_MINE(eth_prepare_mac_addr_change)
CL_MINE(eth_commit_mac_addr_change)
CL_MINE(net_dim_get_rx_irq_moder)
CL_MINE(net_dim_free_irq_moder)
CL_MINE(net_failover_destroy)
CL_MINE(net_dim_init_irq_moder)
CL_MINE(net_dim_setting)
CL_MINE(net_failover_create)
CL_MINE(net_dim)
CL_MINE(raw_notifier_chain_unregister)
CL_MINE(static_key_slow_dec_cpuslocked)
CL_MINE(device_rename)
CL_MINE(netdev_change_owner)
CL_MINE(vlan_do_receive)
CL_MINE(dev_dmabuf_uninstall)
CL_MINE(eth_mac_addr)
CL_MINE(bpf_token_put)
CL_MINE(sha1_init)
CL_MINE(sha1_transform)
CL_MINE(prandom_seed_full_state)
CL_MINE(prandom_u32_state)
CL_MINE(mp_dmabuf_devmem_init)
CL_MINE(mp_dmabuf_devmem_release_page)
CL_MINE(mp_dmabuf_devmem_alloc_netmems)
CL_MINE(mp_dmabuf_devmem_destroy)
CL_MINE(netdev_nl_sock_priv_destroy)
CL_MINE(netdev_nl_sock_priv_init)
CL_MINE(netdev_nl_dev_get_doit)
CL_MINE(netdev_nl_dev_get_dumpit)
CL_MINE(netdev_nl_queue_get_doit)
CL_MINE(netdev_nl_queue_get_dumpit)
CL_MINE(netdev_nl_napi_get_doit)
CL_MINE(netdev_nl_napi_get_dumpit)
CL_MINE(netdev_nl_qstats_get_dumpit)
CL_MINE(netdev_nl_bind_rx_doit)
CL_MINE(add_wait_queue_exclusive)
CL_MINE(security_secid_to_secctx)
CL_MINE(security_release_secctx)
CL_MINE(yield)
CL_MINE(security_netlink_send)
CL_MINE(anon_inode_getfile)
CL_MINE(gen_kill_estimator)
CL_MINE(gen_estimator_read)
CL_MINE(gen_new_estimator)
CL_MINE(gen_replace_estimator)
CL_MINE(tcp_bpf_update_proto)
CL_MINE(xfrm4_udp_encap_rcv)
CL_MINE(xfrm4_gro_udp_encap_rcv)
CL_MINE(udp_bpf_update_proto)
CL_MINE(ip_forward)
CL_MINE(nexthop_free_rcu)
CL_MINE(fib_check_nexthop)
CL_MINE(rtm_getroute_parse_ip_proto)
CL_MINE(vm_insert_pages)
CL_MINE(reqsk_fastopen_remove)
CL_MINE(inet6_ehashfn)
CL_MINE(ipv6_skip_exthdr)
CL_MINE(inet_proto_csum_replace4)
CL_MINE(inet_proto_csum_replace16)
CL_MINE(f_getown)
CL_MINE(open_related_ns)
CL_MINE(f_setown)
CL_MINE(io_uring_cmd_sock)
CL_MINE(ethtool_notify)
CL_MINE(flow_rule_alloc)
CL_MINE(sk_msg_recvmsg)
CL_MINE(sk_msg_is_readable)
CL_MINE(dentry_open)
CL_MINE(io_is_uring_fops)
CL_MINE(put_cmsg_compat)
CL_MINE(receive_fd)
CL_MINE(scm_detach_fds_compat)
CL_MINE(xfrm_sysctl_fini)
CL_MINE(xfrm_replay_notify)
CL_MINE(xfrm_init_replay)
CL_MINE(xfrm_replay_recheck)
CL_MINE(xfrm_replay_advance)
CL_MINE(xfrm_replay_check)
CL_MINE(xfrm_replay_seqhi)
CL_MINE(bpf_token_capable)
CL_MINE(__inet6_lookup_established)
CL_MINE(inet6_lookup_listener)
CL_MINE(inet_proto_csum_replace_by_diff)
CL_MINE(inet6_csk_update_pmtu)
CL_MINE(inet6_hash_connect)
CL_MINE(inet6_csk_route_req)
CL_MINE(inet6_lookup_reuseport)
CL_MINE(inet6_hash)
CL_MINE(inet6_csk_xmit)
CL_MINE(inet6_csk_addr2sockaddr)
CL_MINE(__static_key_slow_dec_deferred)
CL_MINE(nf_setsockopt)
CL_MINE(__static_key_deferred_flush)
CL_MINE(ip6_dst_hoplimit)
CL_MINE(nf_getsockopt)
CL_MINE(jump_label_update_timeout)
CL_MINE(xfrm6_local_rxpmtu)
CL_MINE(xfrm6_udp_encap_rcv)
CL_MINE(xfrm6_gro_udp_encap_rcv)
CL_MINE(inet6_lookup_run_sk_lookup)
CL_MINE(udp6_csum_init)
CL_MINE(ipv6_ext_hdr)
CL_MINE(in6_pton)
CL_MINE(ipv6_find_hdr)
CL_MINE(ipv6_rpl_srh_decompress)
CL_MINE(ipv6_rpl_srh_compress)
CL_MINE(ipv6_proxy_select_ident)
CL_MINE(ip6_local_out)
CL_MINE(nexthop_for_each_fib6_nh)
CL_MINE(nexthop_select_path)
CL_MINE(fib6_check_nexthop)
CL_MINE(__ip6_local_out)
CL_MINE(bpf_verifier_vlog)
CL_MINE(bpf_log)
CL_MINE(bpf_vlog_finalize)
CL_MINE(verbose_linfo)
CL_MINE(reg_type_str)
CL_MINE(kvrealloc_noprof)
CL_MINE(tnum_strn)
CL_MINE(print_verifier_state)
CL_MINE(anon_inode_getfd)
CL_MINE(kallsyms_lookup_name)
CL_MINE(bpf_vlog_init)
CL_MINE(__bpf_core_types_are_compat)
CL_MINE(__bpf_core_types_match)
CL_MINE(bpf_core_calc_relo_insn)
CL_MINE(bpf_core_patch_insn)
CL_MINE(bpf_prog_test_run_sk_lookup)
CL_MINE(bpf_prog_test_run_flow_dissector)
CL_MINE(bpf_prog_test_run_skb)
CL_MINE(bpf_prog_test_run_xdp)
CL_MINE(security_bpf_prog_free)
CL_MINE(close_fd)
CL_MINE(kallsyms_show_value)
CL_MINE(security_bpf_map_free)
CL_MINE(security_bpf_prog)
CL_MINE(security_bpf)
CL_MINE(bpf_token_create)
CL_MINE(bpf_token_allow_prog_type)
CL_MINE(bpf_obj_pin_user)
CL_MINE(bpf_obj_get_user)
CL_MINE(security_bpf_prog_load)
CL_MINE(security_bpf_map)
CL_MINE(security_bpf_map_create)
CL_MINE(bpf_token_get_from_fd)
CL_MINE(bpf_token_allow_cmd)
CL_MINE(bpf_token_allow_map_type)
CL_MINE(bpf_lru_push_free)
CL_MINE(pcpu_freelist_push)
CL_MINE(remap_vmalloc_range)
CL_MINE(pcpu_freelist_init)
CL_MINE(pcpu_freelist_populate)
CL_MINE(pcpu_freelist_pop)
CL_MINE(bpf_lru_init)
CL_MINE(bpf_lru_populate)
CL_MINE(cpu_mitigations_off)
CL_MINE(pcpu_freelist_destroy)
CL_MINE(bpf_lru_destroy)
CL_MINE(bpf_map_meta_alloc)
CL_MINE(bpf_map_meta_free)
CL_MINE(bpf_map_meta_equal)
CL_MINE(__pcpu_freelist_pop)
CL_MINE(bpf_lru_pop_free)
CL_MINE(bpf_map_fd_get_ptr)
CL_MINE(bpf_map_fd_put_ptr)
CL_MINE(bpf_map_fd_sys_lookup_elem)
CL_MINE(ns_get_path_cb)
CL_MINE(iter_state_str)
CL_MINE(dynptr_type_str)
CL_MINE(print_insn_state)
CL_MINE(bpf_local_storage_update)
CL_MINE(bpf_local_storage_map_free)
CL_MINE(bpf_local_storage_map_alloc)
CL_MINE(__bpf_local_storage_insert_cache)
CL_MINE(bpf_selem_unlink)
CL_MINE(bpf_local_storage_destroy)
CL_MINE(bpf_selem_alloc)
CL_MINE(bpf_selem_link_map)
CL_MINE(bpf_selem_link_storage_nolock)
CL_MINE(bpf_local_storage_alloc)
CL_MINE(bpf_selem_free)
CL_MINE(sk_psock_drop)
CL_MINE(sk_psock_stop_verdict)
CL_MINE(sk_psock_link_pop)
CL_MINE(sk_psock_stop)
CL_MINE(sk_psock_init)
CL_MINE(sk_psock_start_verdict)
CL_MINE(bpf_local_storage_map_alloc_check)
CL_MINE(bpf_local_storage_map_check_btf)
CL_MINE(bpf_local_storage_map_mem_usage)
CL_MINE(bpf_mprog_detach)
CL_MINE(bpf_mprog_attach)
CL_MINE(bpf_mprog_query)
CL_MINE(pidfd_get_pid)
CL_MINE(vmap)
CL_MINE(build_id_parse)
CL_MINE(build_id_parse_nofault)
CL_MINE(stack_trace_save_tsk)
CL_MINE(iter_type_str)
CL_MINE(uprobe_get_trampoline_vaddr)
CL_MINE(perf_output_copy)
CL_MINE(find_ge_pid)
CL_MINE(ftrace_profile_free_filter)
CL_MINE(rb_free)
CL_MINE(perf_reg_value)
CL_MINE(ns_get_path)
CL_MINE(perf_trace_init)
CL_MINE(perf_trace_destroy)
CL_MINE(get_task_mm)
CL_MINE(bitmap_print_to_pagebuf)
CL_MINE(perf_mmap_to_page)
CL_MINE(trace_event_get_offsets)
CL_MINE(sysfs_update_groups)
CL_MINE(perf_uprobe_init)
CL_MINE(perf_uprobe_destroy)
CL_MINE(security_perf_event_open)
CL_MINE(perf_reg_validate)
CL_MINE(security_perf_event_read)
CL_MINE(security_perf_event_alloc)
CL_MINE(perf_output_begin)
CL_MINE(perf_output_end)
CL_MINE(rb_alloc_aux)
CL_MINE(rb_alloc)
CL_MINE(security_perf_event_free)
CL_MINE(send_sig_perf)
CL_MINE(match_token)
CL_MINE(ftrace_profile_set_filter)
CL_MINE(match_strdup)
CL_MINE(security_perf_event_write)
CL_MINE(rb_free_aux)
CL_MINE(perf_output_skip)
CL_MINE(perf_reg_abi)
CL_MINE(perf_get_regs_user)
CL_MINE(perf_output_begin_forward)
CL_MINE(perf_output_begin_backward)
CL_MINE(filter_match_preds)
CL_MINE(perf_trace_buf_update)
CL_MINE(ktime_get_raw_fast_ns)
CL_MINE(bpf_prog_test_run_syscall)
CL_MINE(bpf_vlog_reset)
CL_MINE(perf_trace_add)
CL_MINE(perf_trace_del)
CL_MINE(trace_set_clr_event)
CL_MINE(uprobe_unregister_nosync)
CL_MINE(uprobe_unregister_sync)
CL_MINE(bpf_prog_test_run_nf)
CL_MINE(lookup_user_key)
CL_MINE(tracepoint_probe_register_prio_may_exist)
CL_MINE(tracepoint_probe_unregister)
CL_MINE(bpf_get_uprobe_info)
CL_MINE(uprobe_register)
CL_MINE(bpf_prog_test_run_raw_tp)
CL_MINE(kallsyms_lookup)
CL_MINE(ktime_get_boot_fast_ns)
CL_MINE(ktime_get_tai_fast_ns)
CL_MINE(ns_match)
CL_MINE(access_process_vm)
CL_MINE(proc_sys_evict_inode)
CL_MINE(make_empty_dir_inode)
CL_MINE(get_cpu_iowait_time_us)
CL_MINE(get_cpu_idle_time_us)
CL_MINE(getboottime64)
CL_MINE(kstat_irqs_usr)
CL_MINE(nr_running)
CL_MINE(nr_iowait)
CL_MINE(oom_badness)
CL_MINE(get_wchan)
CL_MINE(lookup_symbol_name)
CL_MINE(access_remote_vm)
CL_MINE(task_current_syscall)
CL_MINE(proc_sched_set_task)
CL_MINE(proc_timens_show_offsets)
CL_MINE(proc_sched_show_task)
CL_MINE(proc_timens_set_offset)
CL_MINE(process_shares_mm)
CL_MINE(find_lock_task_mm)
CL_MINE(mm_access)
CL_MINE(ns_get_name)
CL_MINE(readlink_copy)
CL_MINE(walk_page_vma)
CL_MINE(walk_page_range)
CL_MINE(proc_uid_map_write)
CL_MINE(proc_gid_map_write)
CL_MINE(proc_projid_map_write)
CL_MINE(show_fd_locks)
CL_MINE(get_kthread_comm)
CL_MINE(wq_worker_comm)
CL_MINE(is_path_reachable)
CL_MINE(tty_get_pgrp)
CL_MINE(tty_devnum)
CL_MINE(task_prio)
CL_MINE(task_cputime_adjusted)
CL_MINE(get_task_cred)
CL_MINE(d_hash_and_lookup)
CL_MINE(__genradix_free)
CL_MINE(__genradix_ptr_alloc)
CL_MINE(__genradix_ptr)
CL_MINE(arch_prctl_spec_ctrl_get)
CL_MINE(proc_setgroups_write)
CL_MINE(ns_capable_noaudit)
CL_MINE(task_user_regset_view)
CL_MINE(copy_regset_to_user)
CL_MINE(ptracer_capable)
CL_MINE(bit_wait)
CL_MINE(send_sig_info)
CL_MINE(arch_ptrace)
CL_MINE(copy_siginfo_from_user)
CL_MINE(seccomp_get_metadata)
CL_MINE(seccomp_get_filter)
CL_MINE(ptrace_disable)
CL_MINE(__copy_siginfo_to_user32)
CL_MINE(copy_siginfo_from_user32)
CL_MINE(compat_arch_ptrace)
CL_MINE(cpudl_find)
