# Makefile for `cl - clinux`

obj-y += raw.o

#obj-y += main.o
#obj-y += cl_mine.o
#obj-y += cl_dummy.o
#obj-y += mount_ops.o
#obj-y += cl_syscalls.o
#obj-y += test_block.o
#obj-y += test_fs.o
#obj-y += benchmark.o
