# Makefile for `kernel/irq`

obj-y += handle.o
obj-y += irqdomain.o
obj-y += irqdesc.o
obj-y += manage.o
obj-y += chip.o
obj-y += dummychip.o
obj-y += resend.o
obj-y += ipi-mux.o

#obj-y += msi.o spurious.o
#obj-y += devres.o pm.o affinity.o
#obj-y += ipi.o
