# Makefile for `kernel/irq`

obj-y += handle.o

#obj-y += irqdomain.o irqdesc.o manage.o dummychip.o
#obj-y += resend.o chip.o msi.o spurious.o
#obj-y += devres.o pm.o affinity.o
#obj-y += ipi.o ipi-mux.o
