# Makefile for `kernel/irq`

obj-y += handle.o
obj-y += irqdomain.o
obj-y += irqdesc.o
obj-y += manage.o
obj-y += chip.o
obj-y += dummychip.o
obj-y += resend.o
obj-y += ipi.o
obj-y += ipi-mux.o
obj-y += cpuhotplug.o
obj-y += pm.o
obj-y += proc.o
obj-y += spurious.o
obj-y += msi.o

#obj-y += devres.o affinity.o
