# Makefile for `fs`

obj-y += fs_struct.o
obj-y += namei.o
obj-y += namespace.o
obj-y += exec.o
obj-y += fs-writeback.o

#obj-y += inode.o libfs.o filesystems.o dcache.o sync.o
#obj-y += fs_context.o super.o mnt_idmapping.o
#obj-y += buffer.o file_table.o bad_inode.o mbcache.o
#obj-y += read_write.o readdir.o posix_acl.o
#obj-y += stat.o char_dev.o open.o file.o
#obj-y += locks.o d_path.o attr.o
#
#obj-y += iomap/
#obj-y += proc/
#obj-y += ext4/
#obj-y += jbd2/
