# Makefile for `fs`

obj-y += fs_struct.o
obj-y += inode.o
obj-y += super.o
obj-y += namei.o
obj-y += dcache.o
obj-y += namespace.o
obj-y += exec.o
obj-y += fs-writeback.o
obj-y += filesystems.o
obj-y += fs_context.o
obj-y += fs_parser.o
obj-y += libfs.o
obj-y += mnt_idmapping.o
obj-y += xattr.o
obj-y += file_table.o
obj-y += d_path.o
obj-y += buffer.o
obj-y += read_write.o
obj-y += sync.o
obj-y += mpage.o

#obj-y += bad_inode.o mbcache.o
#obj-y += readdir.o posix_acl.o
#obj-y += stat.o char_dev.o open.o file.o
#obj-y += locks.o attr.o


#obj-y += proc/
#obj-y += ext4/
#obj-y += jbd2/

obj-y += iomap/
