# Makefile for `fs`

obj-y += inode.o libfs.o filesystems.o dcache.o sync.o
obj-y += namespace.o fs_context.o super.o mnt_idmapping.o
obj-y += buffer.o file_table.o bad_inode.o mbcache.o
obj-y += read_write.o fs-writeback.o readdir.o posix_acl.o
obj-y += stat.o char_dev.o open.o namei.o file.o exec.o
obj-y += fs_struct.o locks.o d_path.o attr.o

obj-y += ext4/
obj-y += jbd2/
