#include <linux/printk.h>
#include "adaptor.h"

// virtio_blk
CL_MINE(blk_cleanup_queue)
CL_MINE(blk_execute_rq)
CL_MINE(blk_get_request)
CL_MINE(blk_mq_free_tag_set)
CL_MINE(blk_mq_stop_hw_queue)
CL_MINE(blk_put_request)
CL_MINE(blk_queue_alignment_offset)
CL_MINE(blk_queue_io_min)
CL_MINE(blk_queue_io_opt)
CL_MINE(blk_queue_physical_block_size)
CL_MINE(blk_rq_map_kern)
CL_MINE(del_gendisk)
CL_MINE(mutex_destroy)
CL_MINE(param_ops_uint)
CL_MINE(put_disk)
CL_MINE(refcount_warn_saturate)
CL_MINE(set_disk_ro)
CL_MINE(unregister_blkdev)

CL_MINE(blk_mq_requeue_request)
CL_MINE(blk_mq_end_request_batch)
CL_MINE(queue_limits_commit_update)
CL_MINE(blk_status_to_errno)
CL_MINE(blk_mq_alloc_request)
CL_MINE(blk_mq_unfreeze_queue)
CL_MINE(blk_mq_quiesce_queue_nowait)
CL_MINE(blk_mq_freeze_queue)
CL_MINE(destroy_workqueue)
CL_MINE(blk_mq_unquiesce_queue)
CL_MINE(flush_work)
CL_MINE(queue_work_on)

// vsprintf
CL_MINE(siphash_1u64)

// virtio_mmio
CL_MINE(devm_kfree)
CL_MINE(free_irq)
CL_MINE(platform_driver_unregister)

// virtio
CL_MINE(add_uevent_var)
CL_MINE(bus_unregister)
CL_MINE(device_unregister)
CL_MINE(driver_unregister)
CL_MINE(panic)

// virtio_ring
CL_MINE(dev_driver_string)
CL_MINE(dma_alloc_attrs)
CL_MINE(dma_free_attrs)
CL_MINE(dma_map_page_attrs)
CL_MINE(dma_max_mapping_size)
CL_MINE(dma_unmap_page_attrs)
CL_MINE(free_pages_exact)
CL_MINE(is_vmalloc_addr)

// string_helpers
CL_MINE(get_cmdline)
CL_MINE(file_path)

// plic
CL_MINE(disable_percpu_irq)
CL_MINE(iounmap)
CL_MINE(irq_domain_free_irqs_top)

CL_MINE(acpi_dev_clear_dependencies)
CL_MINE(acpi_disabled)
CL_MINE(cpu_bit_bitmap)
CL_MINE(handle_edge_irq)
CL_MINE(irq_domain_translate_twocell)
CL_MINE(riscv_acpi_get_gsi_info)

// ext2/inode
CL_MINE(__blockdev_direct_IO)
CL_MINE(block_is_partially_uptodate)
CL_MINE(block_truncate_page)
CL_MINE(block_write_begin)
CL_MINE(buffer_migrate_page)
CL_MINE(clear_inode)
CL_MINE(current_time)
CL_MINE(fs_overflowgid)
CL_MINE(fs_overflowuid)
CL_MINE(generic_block_bmap)
CL_MINE(generic_block_fiemap)
CL_MINE(generic_error_remove_page)
CL_MINE(generic_fillattr)
CL_MINE(iget_failed)
CL_MINE(init_special_inode)
CL_MINE(inode_dio_wait)
CL_MINE(inode_needs_sync)
CL_MINE(inode_nohighmem)
CL_MINE(invalidate_inode_buffers)
CL_MINE(mark_buffer_dirty_inode)
CL_MINE(mpage_readahead)
CL_MINE(mpage_writepages)
CL_MINE(nobh_truncate_page)
CL_MINE(nobh_write_begin)
CL_MINE(nobh_write_end)
CL_MINE(nobh_writepage)
CL_MINE(posix_acl_chmod)
CL_MINE(__sb_end_write)
CL_MINE(__sb_start_write)
CL_MINE(setattr_copy)
CL_MINE(setattr_prepare)
CL_MINE(sync_inode_metadata)
CL_MINE(sync_mapping_buffers)
CL_MINE(truncate_inode_pages_final)
CL_MINE(truncate_pagecache)
CL_MINE(truncate_setsize)

// ext2/namei
CL_MINE(d_instantiate_new)
CL_MINE(discard_new_inode)
CL_MINE(d_obtain_alias)
CL_MINE(drop_nlink)
CL_MINE(d_tmpfile)
CL_MINE(inc_nlink)
CL_MINE(page_symlink)

// ext2/ioctl
CL_MINE(inode_owner_or_capable)
CL_MINE(mnt_drop_write_file)
CL_MINE(mnt_want_write_file)
CL_MINE(vfs_ioc_setflags_prepare)

// ext2/file
CL_MINE(generic_file_fsync)
CL_MINE(generic_file_llseek)
CL_MINE(generic_file_mmap)
CL_MINE(generic_file_open)
CL_MINE(generic_file_splice_read)
CL_MINE(generic_file_write_iter)
CL_MINE(iter_file_splice_write)

// ext2/balloc
CL_MINE(bh_submit_read)
CL_MINE(capable)
CL_MINE(in_group_p)
CL_MINE(inode_add_bytes)
CL_MINE(inode_sub_bytes)
CL_MINE(memscan)

// ext2/ialloc
CL_MINE(__breadahead)
CL_MINE(inode_init_owner)
CL_MINE(insert_inode_locked)
CL_MINE(make_bad_inode)
CL_MINE(prandom_u32)

// ext2/super
CL_MINE(from_kgid_munged)
CL_MINE(from_kuid_munged)
CL_MINE(generic_fh_to_dentry)
CL_MINE(generic_fh_to_parent)
CL_MINE(init_user_ns)
CL_MINE(match_int)
CL_MINE(match_token)
CL_MINE(rcu_barrier)
CL_MINE(seq_printf)
CL_MINE(seq_puts)
CL_MINE(strsep)
CL_MINE(sync_filesystem)
CL_MINE(unregister_filesystem)

// ext2/dir
CL_MINE(generic_read_dir)
CL_MINE(__lock_page)
CL_MINE(fs_umode_to_ftype)
CL_MINE(write_one_page)

// ext2/symlink
CL_MINE(simple_get_link)
CL_MINE(page_get_link)

// ext4
CL_MINE(krealloc_noprof)
CL_MINE(d_alloc)
CL_MINE(d_drop)
CL_MINE(buffer_migrate_folio)
CL_MINE(generic_encode_ino32_fh)
CL_MINE(fs_param_is_gid)
CL_MINE(fs_param_is_uid)
CL_MINE(fs_param_is_u32)
CL_MINE(fs_param_is_enum)
CL_MINE(fs_param_is_blockdev)
CL_MINE(fs_param_is_string)
CL_MINE(fs_param_is_s32)
CL_MINE(folio_wait_stable)
CL_MINE(make_vfsgid)
CL_MINE(make_vfsuid)
CL_MINE(from_vfsgid)
CL_MINE(__seq_puts)
CL_MINE(system_unbound_wq)
CL_MINE(ext4_orphan_file_block_trigger)
CL_MINE(nop_posix_acl_access)
CL_MINE(nop_posix_acl_default)
CL_MINE(ext4_xattr_security_handler)
CL_MINE(ext4_init_orphan_info)
CL_MINE(ext4_orphan_cleanup)
CL_MINE(generic_error_remove_folio)
CL_MINE(__folio_lock)
CL_MINE(folio_zero_new_buffers)
CL_MINE(ext4_orphan_file_empty)
CL_MINE(folio_mkclean)
CL_MINE(fsnotify)
CL_MINE(ext4_release_orphan_info)
CL_MINE(timer_shutdown_sync)
CL_MINE(__fs_parse)
CL_MINE(fs_lookup_param)
CL_MINE(fs_holder_ops)
CL_MINE(__bread_gfp)
CL_MINE(tag_pages_for_writeback)
CL_MINE(ext4_set_acl)
CL_MINE(iocb_bio_iopoll)
CL_MINE(folio_clear_dirty_for_io)
CL_MINE(__flush_workqueue)
CL_MINE(system_wq)
CL_MINE(get_random_u16)
CL_MINE(ktime_get_with_offset)
CL_MINE(nsecs_to_jiffies)
CL_MINE(mod_timer)
CL_MINE(filemap_get_folios_tag)
CL_MINE(fdget)
CL_MINE(fileattr_fill_flags)
CL_MINE(from_kprojid)
CL_MINE(d_splice_alias)
CL_MINE(get_inode_acl)
CL_MINE(kvfree_call_rcu)
CL_MINE(from_vfsuid)
CL_MINE(ext4_init_acl)
CL_MINE(ext4_init_security)
CL_MINE(mb_cache_entry_delete_or_get)
CL_MINE(mb_cache_entry_wait_unused)
CL_MINE(kmemdup_noprof)
CL_MINE(iomap_swapfile_activate)
CL_MINE(filemap_dirty_folio)
CL_MINE(filemap_splice_read)
CL_MINE(generic_write_checks)
CL_MINE(inode_query_iversion)
CL_MINE(generic_file_read_iter)
CL_MINE(iov_iter_alignment)
CL_MINE(touch_atime)
CL_MINE(down_read_trylock)
CL_MINE(file_modified)
CL_MINE(generic_perform_write)
CL_MINE(vfs_fsync_range)
CL_MINE(bdev_freeze)
CL_MINE(bdev_thaw)
CL_MINE(__might_fault)
CL_MINE(ext4_get_acl)
CL_MINE(inode_set_ctime_current)
CL_MINE(inode_maybe_inc_iversion)
CL_MINE(ext4_orphan_add)
CL_MINE(ext4_orphan_del)
CL_MINE(folio_mark_dirty)
CL_MINE(get_random_u32)
CL_MINE(kfree_link)
CL_MINE(from_kgid)
CL_MINE(folio_wait_writeback)
CL_MINE(clear_nlink)
CL_MINE(sync_dirty_buffer)
CL_MINE(finish_open)
CL_MINE(page_cache_sync_ra)
CL_MINE(bio_devname)
CL_MINE(blkdev_get_by_dev)
CL_MINE(__blkdev_issue_discard)
CL_MINE(blkdev_issue_discard)
CL_MINE(blkdev_issue_zeroout)
CL_MINE(blkdev_put)
CL_MINE(block_commit_write)
CL_MINE(block_page_mkwrite)
CL_MINE(block_read_full_page)
CL_MINE(complete)
CL_MINE(_copy_from_user)
CL_MINE(_copy_to_user)
CL_MINE(crc16)
CL_MINE(d_find_any_alias)
CL_MINE(dget_parent)
CL_MINE(d_mark_dontcache)
CL_MINE(down_write_trylock)
CL_MINE(d_path)
CL_MINE(dump_stack)
CL_MINE(__fdget)
CL_MINE(fiemap_fill_next_extent)
CL_MINE(fiemap_prep)
CL_MINE(filemap_fault)
CL_MINE(filemap_flush)
CL_MINE(filemap_map_pages)
CL_MINE(__filemap_set_wb_err)
CL_MINE(file_update_time)
CL_MINE(find_inode_by_ino_rcu)
CL_MINE(flush_workqueue)
CL_MINE(free_percpu)
CL_MINE(freeze_bdev)
CL_MINE(generic_file_llseek_size)
CL_MINE(get_zeroed_page)
CL_MINE(init_uts_ns)
CL_MINE(inode_io_list_del)
CL_MINE(inode_newsize_ok)
CL_MINE(iomap_dio_iopoll)
CL_MINE(iomap_dio_rw)
CL_MINE(iomap_fiemap)
CL_MINE(iomap_seek_data)
CL_MINE(iomap_seek_hole)
CL_MINE(jiffies)
CL_MINE(kern_path)
CL_MINE(kstrndup)
CL_MINE(kthread_should_stop)
CL_MINE(kthread_stop)
CL_MINE(kunit_binary_assert_format)
CL_MINE(kunit_do_assertion)
CL_MINE(__kunit_test_suites_exit)
CL_MINE(__kunit_test_suites_init)
CL_MINE(list_sort)
CL_MINE(lock_two_nondirectories)
CL_MINE(match_strdup)
CL_MINE(mb_cache_destroy)
CL_MINE(mb_cache_entry_create)
CL_MINE(mb_cache_entry_delete)
CL_MINE(mb_cache_entry_find_first)
CL_MINE(mb_cache_entry_find_next)
CL_MINE(__mb_cache_entry_free)
CL_MINE(mb_cache_entry_get)
CL_MINE(mb_cache_entry_touch)
CL_MINE(memchr_inv)

CL_MINE(io_schedule_timeout)

CL_MINE(memweight)
CL_MINE(noop_backing_dev_info)
CL_MINE(noop_direct_IO)
CL_MINE(pagecache_isize_extended)
CL_MINE(page_cache_readahead_unbounded)
CL_MINE(page_cache_sync_readahead)
CL_MINE(pagecache_write_begin)
CL_MINE(pagecache_write_end)
CL_MINE(__page_symlink)
CL_MINE(pagevec_lookup_range)
CL_MINE(path_put)
CL_MINE(PDE_DATA)
CL_MINE(__percpu_down_read)
CL_MINE(percpu_down_write)
CL_MINE(percpu_free_rwsem)
CL_MINE(percpu_up_write)
CL_MINE(_raw_write_trylock)
CL_MINE(rcuwait_wake_up)
CL_MINE(remove_proc_subtree)
CL_MINE(schedule_timeout_interruptible)
CL_MINE(schedule_timeout_uninterruptible)
CL_MINE(__set_page_dirty_buffers)
CL_MINE(strlcpy)
CL_MINE(synchronize_rcu)
CL_MINE(system_state)
CL_MINE(__task_pid_nr_ns)
CL_MINE(thaw_bdev)
CL_MINE(truncate_pagecache_range)
CL_MINE(try_to_writeback_inodes_sb)
CL_MINE(unlock_two_nondirectories)
CL_MINE(unregister_shrinker)
CL_MINE(vfs_ioc_fssetxattr_check)
CL_MINE(vfs_setpos)
CL_MINE(wait_for_completion)

CL_MINE(folio_end_writeback)
CL_MINE(folio_redirty_for_writepage)
CL_MINE(__folio_start_writeback)
CL_MINE(bio_associate_blkg_from_css)
CL_MINE(bio_add_folio)
CL_MINE(wbc_account_cgroup_owner)
CL_MINE(kstrtoull)
CL_MINE(kstrtouint)
CL_MINE(__percpu_counter_sum)
CL_MINE(file_write_and_wait_range)
CL_MINE(file_check_and_advance_wb_err)
CL_MINE(sysfs_notify)
CL_MINE(generic_buffers_fsync_noflush)
CL_MINE(proc_create_single_data)
CL_MINE(proc_create_seq_private)
CL_MINE(from_kuid)

// jbd2
CL_MINE(__bforget)
CL_MINE(crc32_be)
CL_MINE(filemap_fdatawait_range_keep_errors)
CL_MINE(filemap_fdatawrite_range)
CL_MINE(__get_free_pages)
CL_MINE(jiffies_to_msecs)
CL_MINE(remove_proc_entry)
CL_MINE(schedule_hrtimeout)
CL_MINE(seq_lseek)
CL_MINE(seq_open)
CL_MINE(seq_read)
CL_MINE(seq_release)
CL_MINE(write_dirty_buffer)

CL_MINE(mark_buffer_dirty)
CL_MINE(blkdev_issue_flush)
CL_MINE(ktime_get_coarse_real_ts64)
CL_MINE(percpu_counter_batch)
CL_MINE(round_jiffies_up)
CL_MINE(add_timer)
CL_MINE(__bh_read_batch)
CL_MINE(mutex_lock_io)
CL_MINE(__cond_resched_lock)

CL_MINE(wake_bit_function)
CL_MINE(timer_delete_sync)
CL_MINE(freezing_slow_path)
CL_MINE(__refrigerator)
CL_MINE(end_buffer_write_sync)
CL_MINE(mutex_is_locked)
CL_MINE(percpu_counter_destroy_many)

// iov_iter
CL_MINE(kmemdup)
CL_MINE(__clear_user)
CL_MINE(__asm_copy_from_user)
CL_MINE(__asm_copy_to_user)
CL_MINE(page_cache_pipe_buf_ops)
CL_MINE(csum_partial_copy_nocheck)
CL_MINE(get_user_pages_fast)
CL_MINE(rw_copy_check_uvector)
CL_MINE(csum_partial)

CL_MINE(wait_on_page_bit_killable)
CL_MINE(wait_on_page_bit)
CL_MINE(__lock_page_async)

CL_MINE(clean_bdev_aliases)
CL_MINE(page_zero_new_buffers)

CL_MINE(wait_for_completion_io)
CL_MINE(__page_file_index)

CL_MINE(bdi_dev_name)
CL_MINE(rotate_reclaimable_page)
CL_MINE(blk_recalc_rq_segments)
CL_MINE(blk_dump_rq_flags)
CL_MINE(bio_truncate)

CL_MINE(pagevec_remove_exceptionals)
CL_MINE(truncate_inode_page)
CL_MINE(__cancel_dirty_page)
CL_MINE(blk_flush_plug_list)

// vsprintf
CL_MINE(__clk_get_name)
CL_MINE(_ctype)
CL_MINE(execute_with_initialized_rng)
CL_MINE(fwnode_get_nth_parent)
CL_MINE(get_random_bytes)
CL_MINE(gfpflag_names)
CL_MINE(guid_index)
CL_MINE(has_capability_noaudit)
CL_MINE(of_property_read_string)
CL_MINE(pageflag_names)
CL_MINE(_parse_integer_fixup_radix)
CL_MINE(_parse_integer_limit)
CL_MINE(sprint_backtrace)
CL_MINE(sprint_backtrace_build_id)
CL_MINE(sprint_symbol)
CL_MINE(sprint_symbol_build_id)
CL_MINE(sprint_symbol_no_offset)
CL_MINE(time64_to_tm)
CL_MINE(uuid_index)
CL_MINE(vmaflag_names)

// bitmap
CL_MINE(__devm_add_action)

CL_MINE(memdup_user_nul)
CL_MINE(get_options)
CL_MINE(devres_free)

CL_MINE(kmem_cache_free_bulk)
CL_MINE(kmem_cache_alloc_bulk_noprof)
CL_MINE(irq_free_descs)
CL_MINE(handle_bad_irq)

// irq-riscv-intc
CL_MINE(handle_percpu_devid_irq)
CL_MINE(irq_domain_xlate_onecell)
CL_MINE(acpi_set_irq_model)
CL_MINE(riscv_acpi_get_gsi_domain_id)
CL_MINE(acpi_table_parse_madt)
CL_MINE(__irq_domain_alloc_fwnode)
CL_MINE(irq_domain_free_fwnode)

// virtio
CL_MINE(sysfs_emit)
CL_MINE(sysfs_emit_at)
CL_MINE(of_get_next_available_child)

// kobject
CL_MINE(sysfs_remove_groups)
CL_MINE(sysfs_remove_dir)
CL_MINE(kobject_uevent_env)
CL_MINE(sysfs_move_dir_ns)
CL_MINE(sysfs_rename_dir_ns)

// virtio_mmio
CL_MINE(synchronize_irq)
CL_MINE(__dma_sync_single_for_cpu)
CL_MINE(__dma_sync_single_for_device)
CL_MINE(irq_set_irq_wake)
CL_MINE(__dma_need_sync)

// devres
CL_MINE(devm_kstrdup)
CL_MINE(__devm_release_region)
CL_MINE(devres_destroy)

CL_MINE(mem_cgroup_kmem_disabled)
CL_MINE(add_wait_queue)
CL_MINE(remove_wait_queue)
CL_MINE(device_set_deferred_probe_reason)

CL_MINE(async_schedule_node)

CL_MINE(init_srcu_struct)
CL_MINE(cleanup_srcu_struct)
CL_MINE(blk_mq_free_map_and_rqs)
CL_MINE(kvfree)

CL_MINE(prepare_to_wait_exclusive)
CL_MINE(seq_putc)
CL_MINE(seq_write)
CL_MINE(blk_mq_free_rqs)
CL_MINE(blk_mq_free_rq_map)
CL_MINE(blk_mq_destroy_queue)
CL_MINE(blk_put_queue)
CL_MINE(bioset_exit)

// fs/inode
CL_MINE(kill_anon_super)
CL_MINE(generic_delete_inode)
CL_MINE(security_sb_set_mnt_opts)
CL_MINE(fc_drop_locked)

// block/bdev
CL_MINE(block_write_end)
CL_MINE(__folio_put)
CL_MINE(block_write_full_folio)
CL_MINE(write_cache_pages)
CL_MINE(block_dirty_folio)
CL_MINE(buffer_migrate_folio_norefs)
CL_MINE(buffer_check_dirty_writeback)
CL_MINE(elevator_exit)
CL_MINE(blk_unregister_queue)
CL_MINE(rq_qos_exit)

CL_MINE(memblock_alloc_try_nid_raw)
CL_MINE(vmalloc_huge_noprof)
CL_MINE(find_vm_area)
CL_MINE(__mark_inode_dirty)
CL_MINE(__lock_buffer)

// bio
CL_MINE(kmem_cache_destroy)
CL_MINE(blkcg_policy_throtl)
CL_MINE(__blk_throtl_bio)
CL_MINE(bio_split_rw)
CL_MINE(bio_split_zone_append)
CL_MINE(bio_split_discard)
CL_MINE(bio_split_write_zeroes)
CL_MINE(__blk_mq_tag_busy)
CL_MINE(msleep)
CL_MINE(blk_mq_run_hw_queue)

// scatterlist
CL_MINE(unpin_user_page)
CL_MINE(vmalloc_to_page)
CL_MINE(mempool_destroy)
CL_MINE(is_vmalloc_or_module_addr)
CL_MINE(iov_iter_extract_pages)
CL_MINE(iov_iter_advance)

CL_MINE(housekeeping_enabled)
CL_MINE(housekeeping_cpumask)
CL_MINE(ktime_get_mono_fast_ns)
CL_MINE(blkdev_ioctl)
CL_MINE(compat_blkdev_ioctl)
CL_MINE(blkdev_uring_cmd)
CL_MINE(simple_dname)
CL_MINE(__put_cred)
CL_MINE(blkdev_put_no_open)
CL_MINE(bdev_disk_changed)
CL_MINE(__folio_swap_cache_index)
CL_MINE(__mem_cgroup_uncharge)
CL_MINE(workingset_refault)

CL_MINE(wbc_attach_and_unlock_inode)
CL_MINE(do_writepages)
CL_MINE(wbc_detach_inode)
CL_MINE(__inode_attach_wb)

CL_MINE(truncate_inode_partial_folio)
CL_MINE(truncate_inode_folio)
CL_MINE(__folio_cancel_dirty)
CL_MINE(unmap_mapping_folio)
CL_MINE(free_huge_folio)

CL_MINE(kfree_sensitive)
CL_MINE(wait_for_completion_killable_timeout)
CL_MINE(delayed_work_timer_fn)
