# Makefile for `fs/proc`

obj-y += array.o
obj-y += base.o
obj-y += fd.o
obj-y += generic.o
obj-y += inode.o
obj-y += namespaces.o
obj-y += proc_net.o
obj-y += root.o
obj-y += self.o
obj-y += stat.o
obj-y += task_mmu.o
obj-y += thread_self.o
obj-y += uptime.o
obj-y += util.o
