[package]
name = "u_6_0"
version = "0.1.0"
edition = "2021"

[dependencies]
axstd = { workspace = true, features = ["alloc", "paging", "multitask", "sched_cfs"], optional = true }
axlog = { workspace = true }
