# Makefile for `kernel/time`

obj-y += time.o
obj-y += timer.o
obj-y += hrtimer.o
obj-y += tick-sched.o
obj-y += sched_clock.o
obj-y += posix-cpu-timers.o
obj-y += posix-timers.o
obj-y += timekeeping.o
obj-y += ntp.o
obj-y += jiffies.o
obj-y += namespace.o
obj-y += tick-common.o
obj-y += tick-broadcast.o
obj-y += tick-broadcast-hrtimer.o
obj-y += tick-oneshot.o
obj-y += clocksource.o
obj-y += clockevents.o
obj-y += timer_migration.o
obj-y += posix-clock.o
obj-y += alarmtimer.o
