# Makefile for `kernel/time`

obj-y += time.o
obj-y += timer.o
obj-y += hrtimer.o
obj-y += tick-sched.o
obj-y += sched_clock.o
obj-y += posix-cpu-timers.o
obj-y += timekeeping.o
obj-y += ntp.o
obj-y += jiffies.o
