#include "booter.h"

CL_MINE(siphash_1u64)
CL_MINE(_dev_err)
CL_MINE(devm_kfree)
CL_MINE(free_irq)
CL_MINE(kfree)
CL_MINE(kmalloc)
CL_MINE(platform_driver_unregister)
CL_MINE(platform_get_irq)
CL_MINE(put_device)
CL_MINE(_raw_spin_lock_irqsave)
CL_MINE(_raw_spin_unlock_irqrestore)
CL_MINE(request_threaded_irq)

CL_MINE(add_uevent_var)
CL_MINE(alloc_pages_exact)
CL_MINE(bus_unregister)
CL_MINE(dev_driver_string)
CL_MINE(device_unregister)
CL_MINE(dma_alloc_attrs)
CL_MINE(dma_free_attrs)
CL_MINE(dma_map_page_attrs)
CL_MINE(dma_max_mapping_size)
CL_MINE(dma_unmap_page_attrs)
CL_MINE(driver_register)
CL_MINE(driver_unregister)
CL_MINE(free_pages_exact)
CL_MINE(ida_destroy)
CL_MINE(ida_free)
CL_MINE(is_vmalloc_addr)
CL_MINE(__kmalloc)
CL_MINE(panic)
CL_MINE(_raw_spin_lock_irq)
CL_MINE(_raw_spin_unlock_irq)
CL_MINE(sg_next)
CL_MINE(__warn_printk)

CL_MINE(pfn_to_page)
CL_MINE(page_to_pfn)
