# Makefile for `net/ipv6`

obj-y += addrconf_core.o
obj-y += tcp_ipv6.o
obj-y += af_inet6.o
obj-y += ip6_flowlabel.o
obj-y += ipv6_sockglue.o
obj-y += mcast.o
obj-y += raw.o
obj-y += udp.o
obj-y += udplite.o
obj-y += ping.o
obj-y += ndisc.o
obj-y += icmp.o
obj-y += protocol.o
obj-y += netfilter.o
obj-y += route.o
obj-y += ip6_fib.o
obj-y += fib6_notifier.o
obj-y += xfrm6_policy.o
obj-y += xfrm6_state.o
obj-y += xfrm6_protocol.o
