# Makefile for `arch/riscv/lib`

obj-y += delay.o
obj-y += clear_page.o
obj-y += memset.o
obj-y += memcpy.o
obj-y += memmove.o
obj-y += strcmp.o
obj-y += strncmp.o
obj-y += strlen.o
obj-y += tishift.o
#obj-y += xor.o
