# Makefile for `kernel`

obj-y += printk/

#obj-y += resource.o workqueue.o kthread.o
#obj-y += nsproxy.o cpu.o user_namespace.o
#obj-y += panic.o exit.o cred.o softirq.o
#obj-y += extable.o tracepoint.o jump_label.o
#obj-y += irq_work.o params.o reboot.o
#obj-y += notifier.o smp.o smpboot.o async.o
#obj-y += fork.o
#
#obj-y += sched/
#obj-y += locking/
#obj-y += irq/
#obj-y += rcu/
#obj-y += dma/
#obj-y += time/
#obj-y += trace/
