# Makefile for `kernel`

obj-y += printk/
obj-y += sched/
obj-y += locking/
obj-y += dma/
obj-y += entry/
obj-y += irq/
obj-y += rcu/
obj-y += time/

obj-y += panic.o
obj-y += cpu.o
obj-y += fork.o
obj-y += smp.o
obj-y += cred.o
obj-y += extable.o
obj-y += softirq.o
obj-y += jump_label.o

#obj-y += resource.o workqueue.o kthread.o
#obj-y += nsproxy.o user_namespace.o
#obj-y += exit.o
#obj-y += tracepoint.o
#obj-y += irq_work.o params.o reboot.o
#obj-y += notifier.o smpboot.o async.o
#
#obj-y += trace/
