# Makefile for `lib`

obj-y += vsprintf.o
obj-y += string.o
obj-y += find_bit.o
obj-y += ctype.o
obj-y += hexdump.o
obj-y += crc32.o
obj-y += ratelimit.o
obj-y += dump_stack.o
obj-y += sort.o
obj-y += kstrtox.o
obj-y += hweight.o
obj-y += list_debug.o
obj-y += bitmap.o
obj-y += debug_locks.o
obj-y += rbtree.o
obj-y += kasprintf.o

obj-y += math/

#obj-y += string_helpers.o
#obj-y += radix-tree.o maple_tree.o kobject.o klist.o
#obj-y += devres.o errname.o idr.o xarray.o
#obj-y += sbitmap.o lockref.o dec_and_lock.o
#obj-y += sg_pool.o scatterlist.o errseq.o llist.o
#obj-y += iov_iter.o irq_regs.o
#obj-y += percpu_counter.o strncpy_from_user.o seq_buf.o
#obj-y += cmdline.o logic_pio.o
#obj-y += group_cpus.o
