# Makefile for `lib`

obj-y += vsprintf.o string.o hexdump.o ratelimit.o
obj-y += bitmap.o kasprintf.o string_helpers.o list_debug.o
obj-y += radix-tree.o maple_tree.o kobject.o klist.o
obj-y += devres.o hweight.o errname.o idr.o xarray.o
obj-y += sort.o sbitmap.o lockref.o rbtree.o dec_and_lock.o
obj-y += find_bit.o sg_pool.o scatterlist.o errseq.o llist.o
obj-y += crc32.o iov_iter.o irq_regs.o dump_stack.o kstrtox.o
obj-y += percpu_counter.o strncpy_from_user.o ctype.o seq_buf.o
obj-y += cmdline.o logic_pio.o
obj-y += debug_locks.o

obj-y += math/
