# Makefile basic Vars

#CROSS_ = $(ARCH)-linux-musl-
CROSS_ = $(ARCH)-linux-gnu-
CC = $(CROSS_)gcc
AR = $(CROSS_)ar
OBJCOPY = $(CROSS_)objcopy

Q = @

CFLAGS := -isystem /usr/lib/gcc-cross/riscv64-linux-gnu/11/include \
	-I./arch/riscv/include -I./arch/riscv/include/generated \
	-I./include \
	-I./arch/riscv/include/uapi -I./arch/riscv/include/generated/uapi -I./include/uapi -I./include/generated/uapi \
	-include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h \
	-I./cl \
	-nostdinc -fno-PIE -mabi=lp64d -march=rv64imadc_zicsr_zifencei \
	-fshort-wchar -funsigned-char \
	-fno-strict-aliasing \
    -fno-asynchronous-unwind-tables -fno-unwind-tables \
	-fno-builtin -fno-builtin-function \
    -fno-common -fno-stack-protector -mcmodel=medany -D__KERNEL__ \
    -O2 -Wno-stringop-overflow -Wno-format-truncation -Wno-format-security \
    -Werror=implicit-function-declaration -Wno-address-of-packed-member -Werror=implicit-function-declaration \
	-Werror=incompatible-pointer-types \
    -fno-omit-frame-pointer -Wno-frame-address -Wframe-larger-than=2048

ifeq ("$(LOG)", "debug")
CFLAGS += -DDEBUG
endif

_OBJS = $(if $(OBJ_LIST), $(shell cat $(OBJ_LIST) | xargs))

target-stem = $(basename $(patsubst $(curdir)%,%,$@))
