# Makefile for `net`

obj-y += socket.o

obj-y += core/
obj-y += ethtool/
obj-y += ethernet/
obj-y += ipv4/
obj-y += ipv6/
obj-y += netlink/
obj-y += netfilter/
obj-y += sched/
obj-y += l3mdev/
obj-y += xfrm/
obj-y += unix/
