# Makefile for `net/ipv4`

obj-y += af_inet.o
obj-y += arp.o
obj-y += devinet.o
obj-y += igmp.o
obj-y += ip_output.o
obj-y += ping.o
obj-y += protocol.o
obj-y += raw.o
obj-y += route.o
obj-y += tcp_ipv4.o
obj-y += udp.o
