# Makefile for `block`

obj-y += genhd.o blk-mq.o blk-mq-virtio.o
obj-y += blk-mq-cpumap.o blk-mq-tag.o blk-core.o
obj-y += blk-stat.o blk-settings.o bio.o
obj-y += bdev.o fops.o blk-merge.o blk-mq-sched.o
obj-y += blk-flush.o blk-mq-sysfs.o blk-rq-qos.o
obj-y += blk-timeout.o early-lookup.o blk-map.o
obj-y += elevator.o mq-deadline.o
obj-y += partitions/
