# Makefile for `kernel/locking`

obj-y += spinlock.o
obj-y += spinlock_debug.o
obj-y += mutex.o
obj-y += mutex-debug.o
obj-y += rwsem.o
obj-y += rtmutex_api.o
obj-y += percpu-rwsem.o
obj-y += qrwlock.o
